import { NextResponse } from 'next/server';

const products = [
  // Male Fashion
  {
    id: 'prod_001',
    title: 'Classic Slim Fit Denim Jeans',
    description: 'Premium quality slim fit denim jeans with stretch comfort. Perfect for casual and semi-formal occasions.',
    handle: 'slim-fit-denim-jeans',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600',
    images: [
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600' },
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600' },
    ],
    price: { amount: 8999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['28', '30', '32', '34', '36'] },
      { name: 'Color', values: ['Blue', 'Black', 'Navy'] },
    ],
    variants: [
      { id: 'var_001_28_blue', title: '28 / Blue', prices: [{ amount: 8999 }], inventory_quantity: 10, options: { Size: '28', Color: 'Blue' } },
      { id: 'var_001_30_blue', title: '30 / Blue', prices: [{ amount: 8999 }], inventory_quantity: 15, options: { Size: '30', Color: 'Blue' } },
      { id: 'var_001_32_blue', title: '32 / Blue', prices: [{ amount: 8999 }], inventory_quantity: 12, options: { Size: '32', Color: 'Blue' } },
      { id: 'var_001_28_black', title: '28 / Black', prices: [{ amount: 8999 }], inventory_quantity: 8, options: { Size: '28', Color: 'Black' } },
      { id: 'var_001_30_black', title: '30 / Black', prices: [{ amount: 8999 }], inventory_quantity: 10, options: { Size: '30', Color: 'Black' } },
      { id: 'var_001_32_black', title: '32 / Black', prices: [{ amount: 8999 }], inventory_quantity: 10, options: { Size: '32', Color: 'Black' } },
    ],
    collection: { id: 'col_01', title: 'Male Fashion', handle: 'male-fashion' },
    tags: [{ id: 'tag_01', value: 'bestseller' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_002',
    title: 'Premium Cotton Polo Shirt',
    description: 'Soft breathable cotton polo shirt. Classic fit with ribbed collar. Available in multiple colors.',
    handle: 'premium-cotton-polo',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1625910513413-5fc4e5e40687?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1625910513413-5fc4e5e40687?w=600' }],
    price: { amount: 4999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['S', 'M', 'L', 'XL', 'XXL'] },
      { name: 'Color', values: ['White', 'Navy', 'Black', 'Burgundy'] },
    ],
    variants: [
      { id: 'var_002_S_white', title: 'S / White', prices: [{ amount: 4999 }], inventory_quantity: 20, options: { Size: 'S', Color: 'White' } },
      { id: 'var_002_M_white', title: 'M / White', prices: [{ amount: 4999 }], inventory_quantity: 25, options: { Size: 'M', Color: 'White' } },
      { id: 'var_002_L_white', title: 'L / White', prices: [{ amount: 4999 }], inventory_quantity: 20, options: { Size: 'L', Color: 'White' } },
      { id: 'var_002_S_navy', title: 'S / Navy', prices: [{ amount: 4999 }], inventory_quantity: 15, options: { Size: 'S', Color: 'Navy' } },
    ],
    collection: { id: 'col_01', title: 'Male Fashion', handle: 'male-fashion' },
    tags: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_003',
    title: 'Tailored Wool Blend Suit',
    description: 'Elegant two-piece suit in premium wool blend. Perfect for business meetings and special occasions.',
    handle: 'tailored-wool-suit',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600' }],
    price: { amount: 34999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['S', 'M', 'L', 'XL'] },
      { name: 'Color', values: ['Charcoal', 'Navy', 'Black'] },
    ],
    variants: [
      { id: 'var_003_S_charcoal', title: 'S / Charcoal', prices: [{ amount: 34999 }], inventory_quantity: 5, options: { Size: 'S', Color: 'Charcoal' } },
      { id: 'var_003_M_charcoal', title: 'M / Charcoal', prices: [{ amount: 34999 }], inventory_quantity: 5, options: { Size: 'M', Color: 'Charcoal' } },
      { id: 'var_003_L_navy', title: 'L / Navy', prices: [{ amount: 34999 }], inventory_quantity: 5, options: { Size: 'L', Color: 'Navy' } },
    ],
    collection: { id: 'col_01', title: 'Male Fashion', handle: 'male-fashion' },
    tags: [{ id: 'tag_02', value: 'featured' }],
    created_at: new Date().toISOString(),
  },

  // Female Fashion
  {
    id: 'prod_004',
    title: 'Elegant Evening Gown',
    description: 'Stunning floor-length evening gown with sequin details. Perfect for special occasions and galas.',
    handle: 'elegant-evening-gown',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600' }],
    price: { amount: 24999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] },
      { name: 'Color', values: ['Black', 'Red', 'Navy', 'Emerald'] },
    ],
    variants: [
      { id: 'var_004_S_black', title: 'S / Black', prices: [{ amount: 24999 }], inventory_quantity: 5, options: { Size: 'S', Color: 'Black' } },
      { id: 'var_004_M_black', title: 'M / Black', prices: [{ amount: 24999 }], inventory_quantity: 5, options: { Size: 'M', Color: 'Black' } },
      { id: 'var_004_L_red', title: 'L / Red', prices: [{ amount: 24999 }], inventory_quantity: 5, options: { Size: 'L', Color: 'Red' } },
      { id: 'var_004_M_navy', title: 'M / Navy', prices: [{ amount: 24999 }], inventory_quantity: 5, options: { Size: 'M', Color: 'Navy' } },
    ],
    collection: { id: 'col_02', title: 'Female Fashion', handle: 'female-fashion' },
    tags: [{ id: 'tag_03', value: 'featured' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_005',
    title: 'High-Rise Palazzo Trousers',
    description: 'Flowy high-rise palazzo trousers in luxurious fabric. Elegant and comfortable for any occasion.',
    handle: 'high-rise-palazzo-trousers',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600' }],
    price: { amount: 6999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] },
      { name: 'Color', values: ['Beige', 'Black', 'White', 'Brown'] },
    ],
    variants: [
      { id: 'var_005_S_beige', title: 'S / Beige', prices: [{ amount: 6999 }], inventory_quantity: 15, options: { Size: 'S', Color: 'Beige' } },
      { id: 'var_005_M_beige', title: 'M / Beige', prices: [{ amount: 6999 }], inventory_quantity: 20, options: { Size: 'M', Color: 'Beige' } },
      { id: 'var_005_L_black', title: 'L / Black', prices: [{ amount: 6999 }], inventory_quantity: 20, options: { Size: 'L', Color: 'Black' } },
    ],
    collection: { id: 'col_02', title: 'Female Fashion', handle: 'female-fashion' },
    tags: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_006',
    title: 'Silk Wrap Dress',
    description: 'Classic silk wrap dress that flatters every figure. Versatile for work or weekend brunch.',
    handle: 'silk-wrap-dress',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600' }],
    price: { amount: 12999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { name: 'Color', values: ['Navy', 'Burgundy', 'Forest Green'] },
    ],
    variants: [
      { id: 'var_006_S_navy', title: 'S / Navy', prices: [{ amount: 12999 }], inventory_quantity: 10, options: { Size: 'S', Color: 'Navy' } },
      { id: 'var_006_M_navy', title: 'M / Navy', prices: [{ amount: 12999 }], inventory_quantity: 10, options: { Size: 'M', Color: 'Navy' } },
      { id: 'var_006_L_burgundy', title: 'L / Burgundy', prices: [{ amount: 12999 }], inventory_quantity: 10, options: { Size: 'L', Color: 'Burgundy' } },
    ],
    collection: { id: 'col_02', title: 'Female Fashion', handle: 'female-fashion' },
    tags: [{ id: 'tag_04', value: 'bestseller' }],
    created_at: new Date().toISOString(),
  },

  // Kiddies Fashion
  {
    id: 'prod_007',
    title: 'Boys Dinosaur Print T-Shirt',
    description: 'Adorable dino-mite t-shirt for little adventurers. Soft cotton blend, machine washable.',
    handle: 'boys-dinosaur-print-tshirt',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600' }],
    price: { amount: 2499, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'] },
      { name: 'Color', values: ['Green', 'Blue', 'Yellow'] },
    ],
    variants: [
      { id: 'var_007_2-3Y_green', title: '2-3Y / Green', prices: [{ amount: 2499 }], inventory_quantity: 25, options: { Size: '2-3Y', Color: 'Green' } },
      { id: 'var_007_4-5Y_blue', title: '4-5Y / Blue', prices: [{ amount: 2499 }], inventory_quantity: 25, options: { Size: '4-5Y', Color: 'Blue' } },
      { id: 'var_007_6-7Y_green', title: '6-7Y / Green', prices: [{ amount: 2499 }], inventory_quantity: 25, options: { Size: '6-7Y', Color: 'Green' } },
      { id: 'var_007_8-9Y_yellow', title: '8-9Y / Yellow', prices: [{ amount: 2499 }], inventory_quantity: 25, options: { Size: '8-9Y', Color: 'Yellow' } },
    ],
    collection: { id: 'col_03', title: 'Kiddies Fashion', handle: 'kiddies-fashion' },
    tags: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_008',
    title: 'Girls Princess Party Dress',
    description: 'Magical princess dress with tulle skirt and sparkle details. Perfect for birthday parties.',
    handle: 'girls-princess-party-dress',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600' }],
    price: { amount: 5999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'] },
      { name: 'Color', values: ['Pink', 'Purple', 'White', 'Red'] },
    ],
    variants: [
      { id: 'var_008_2-3Y_pink', title: '2-3Y / Pink', prices: [{ amount: 5999 }], inventory_quantity: 15, options: { Size: '2-3Y', Color: 'Pink' } },
      { id: 'var_008_4-5Y_pink', title: '4-5Y / Pink', prices: [{ amount: 5999 }], inventory_quantity: 15, options: { Size: '4-5Y', Color: 'Pink' } },
      { id: 'var_008_6-7Y_purple', title: '6-7Y / Purple', prices: [{ amount: 5999 }], inventory_quantity: 15, options: { Size: '6-7Y', Color: 'Purple' } },
      { id: 'var_008_8-9Y_white', title: '8-9Y / White', prices: [{ amount: 5999 }], inventory_quantity: 20, options: { Size: '8-9Y', Color: 'White' } },
    ],
    collection: { id: 'col_03', title: 'Kiddies Fashion', handle: 'kiddies-fashion' },
    tags: [{ id: 'tag_05', value: 'featured' }],
    created_at: new Date().toISOString(),
  },

  // Skincare Products
  {
    id: 'prod_009',
    title: 'Radiance Glow Serum',
    description: 'Vitamin C brightening serum for luminous, even-toned skin. Reduces dark spots in 4 weeks.',
    handle: 'radiance-glow-serum',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600' }],
    price: { amount: 7999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['15ml', '30ml', '50ml'] },
    ],
    variants: [
      { id: 'var_009_15ml', title: '15ml', prices: [{ amount: 7999 }], inventory_quantity: 40, options: { Size: '15ml' } },
      { id: 'var_009_30ml', title: '30ml', prices: [{ amount: 12999 }], inventory_quantity: 40, options: { Size: '30ml' } },
      { id: 'var_009_50ml', title: '50ml', prices: [{ amount: 17999 }], inventory_quantity: 40, options: { Size: '50ml' } },
    ],
    collection: { id: 'col_04', title: 'Skincare Products', handle: 'skincare' },
    tags: [{ id: 'tag_06', value: 'bestseller' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_010',
    title: 'Luxury Night Cream',
    description: 'Deeply nourishing night cream with retinol and hyaluronic acid. Wake up to younger-looking skin.',
    handle: 'luxury-night-cream',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600' }],
    price: { amount: 12999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['50ml', '100ml'] },
    ],
    variants: [
      { id: 'var_010_50ml', title: '50ml', prices: [{ amount: 12999 }], inventory_quantity: 35, options: { Size: '50ml' } },
      { id: 'var_010_100ml', title: '100ml', prices: [{ amount: 21999 }], inventory_quantity: 40, options: { Size: '100ml' } },
    ],
    collection: { id: 'col_04', title: 'Skincare Products', handle: 'skincare' },
    tags: [{ id: 'tag_07', value: 'featured' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_011',
    title: 'Hydra Boost Moisturizer',
    description: 'Lightweight gel moisturizer for all-day hydration. Non-greasy, fast-absorbing formula.',
    handle: 'hydra-boost-moisturizer',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600' }],
    price: { amount: 4999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['30ml', '50ml'] },
    ],
    variants: [
      { id: 'var_011_30ml', title: '30ml', prices: [{ amount: 4999 }], inventory_quantity: 45, options: { Size: '30ml' } },
      { id: 'var_011_50ml', title: '50ml', prices: [{ amount: 7499 }], inventory_quantity: 45, options: { Size: '50ml' } },
    ],
    collection: { id: 'col_04', title: 'Skincare Products', handle: 'skincare' },
    tags: [],
    created_at: new Date().toISOString(),
  },

  // Luxury Human Hair
  {
    id: 'prod_012',
    title: 'Brazilian Body Wave 360 Lace Wig',
    description: 'Premium 100% human hair 360 lace wig. Natural hairline, can be styled with heat.',
    handle: 'brazilian-body-wave-lace-wig',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600' }],
    price: { amount: 39999, currency_code: 'ngn' },
    options: [
      { name: 'Length', values: ['12 inch', '14 inch', '16 inch', '18 inch'] },
      { name: 'Density', values: ['150%', '180%', '200%'] },
    ],
    variants: [
      { id: 'var_012_12_150', title: '12 inch / 150%', prices: [{ amount: 39999 }], inventory_quantity: 8, options: { Length: '12 inch', Density: '150%' } },
      { id: 'var_012_14_150', title: '14 inch / 150%', prices: [{ amount: 42999 }], inventory_quantity: 8, options: { Length: '14 inch', Density: '150%' } },
      { id: 'var_012_16_180', title: '16 inch / 180%', prices: [{ amount: 49999 }], inventory_quantity: 5, options: { Length: '16 inch', Density: '180%' } },
      { id: 'var_012_18_200', title: '18 inch / 200%', prices: [{ amount: 59999 }], inventory_quantity: 4, options: { Length: '18 inch', Density: '200%' } },
    ],
    collection: { id: 'col_05', title: 'Luxury Human Hair', handle: 'human-hair' },
    tags: [{ id: 'tag_08', value: 'featured' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_013',
    title: 'Malaysian Straight Virgin Hair Bundle',
    description: 'Luxury Malaysian virgin hair, single donor. 100g per bundle, 30 inch length.',
    handle: 'malaysian-virgin-hair-bundle',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600' }],
    price: { amount: 14999, currency_code: 'ngn' },
    options: [
      { name: 'Length', values: ['10 inch', '12 inch', '14 inch', '16 inch', '18 inch'] },
    ],
    variants: [
      { id: 'var_013_10', title: '10 inch', prices: [{ amount: 9999 }], inventory_quantity: 15, options: { Length: '10 inch' } },
      { id: 'var_013_12', title: '12 inch', prices: [{ amount: 12999 }], inventory_quantity: 15, options: { Length: '12 inch' } },
      { id: 'var_013_14', title: '14 inch', prices: [{ amount: 14999 }], inventory_quantity: 10, options: { Length: '14 inch' } },
      { id: 'var_013_16', title: '16 inch', prices: [{ amount: 17999 }], inventory_quantity: 10, options: { Length: '16 inch' } },
    ],
    collection: { id: 'col_05', title: 'Luxury Human Hair', handle: 'human-hair' },
    tags: [{ id: 'tag_09', value: 'bestseller' }],
    created_at: new Date().toISOString(),
  },

  // Bags & Purses
  {
    id: 'prod_015',
    title: 'Italian Leather Tote Bag',
    description: 'Handcrafted Italian leather tote. Spacious interior with zip pocket. Timeless elegance.',
    handle: 'italian-leather-tote',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600' }],
    price: { amount: 19999, currency_code: 'ngn' },
    options: [
      { name: 'Color', values: ['Tan', 'Black', 'Cognac', 'Burgundy'] },
    ],
    variants: [
      { id: 'var_015_tan', title: 'Tan', prices: [{ amount: 19999 }], inventory_quantity: 10, options: { Color: 'Tan' } },
      { id: 'var_015_black', title: 'Black', prices: [{ amount: 19999 }], inventory_quantity: 15, options: { Color: 'Black' } },
      { id: 'var_015_cognac', title: 'Cognac', prices: [{ amount: 19999 }], inventory_quantity: 10, options: { Color: 'Cognac' } },
      { id: 'var_015_burgundy', title: 'Burgundy', prices: [{ amount: 21999 }], inventory_quantity: 5, options: { Color: 'Burgundy' } },
    ],
    collection: { id: 'col_06', title: 'Bags & Purses', handle: 'bags-purses' },
    tags: [{ id: 'tag_10', value: 'featured' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_016',
    title: 'Designer Crossbody Bag',
    description: 'Chic crossbody bag with adjustable strap. Multiple compartments for organization.',
    handle: 'designer-crossbody-bag',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600' }],
    price: { amount: 12999, currency_code: 'ngn' },
    options: [
      { name: 'Color', values: ['Black', 'Nude', 'Red', 'Silver'] },
    ],
    variants: [
      { id: 'var_016_black', title: 'Black', prices: [{ amount: 12999 }], inventory_quantity: 20, options: { Color: 'Black' } },
      { id: 'var_016_nude', title: 'Nude', prices: [{ amount: 12999 }], inventory_quantity: 20, options: { Color: 'Nude' } },
      { id: 'var_016_red', title: 'Red', prices: [{ amount: 12999 }], inventory_quantity: 15, options: { Color: 'Red' } },
    ],
    collection: { id: 'col_06', title: 'Bags & Purses', handle: 'bags-purses' },
    tags: [{ id: 'tag_11', value: 'bestseller' }],
    created_at: new Date().toISOString(),
  },

  // Shoes
  {
    id: 'prod_018',
    title: 'Stiletto Heels',
    description: 'Elegant 4-inch stiletto heels in premium leather. Cushioned insole for all-day comfort.',
    handle: 'stiletto-heels',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600' }],
    price: { amount: 9999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['35', '36', '37', '38', '39', '40', '41'] },
      { name: 'Color', values: ['Black', 'Nude', 'Red'] },
    ],
    variants: [
      { id: 'var_018_35_black', title: '35 / Black', prices: [{ amount: 9999 }], inventory_quantity: 5, options: { Size: '35', Color: 'Black' } },
      { id: 'var_018_36_black', title: '36 / Black', prices: [{ amount: 9999 }], inventory_quantity: 8, options: { Size: '36', Color: 'Black' } },
      { id: 'var_018_37_black', title: '37 / Black', prices: [{ amount: 9999 }], inventory_quantity: 10, options: { Size: '37', Color: 'Black' } },
      { id: 'var_018_38_black', title: '38 / Black', prices: [{ amount: 9999 }], inventory_quantity: 10, options: { Size: '38', Color: 'Black' } },
      { id: 'var_018_37_red', title: '37 / Red', prices: [{ amount: 9999 }], inventory_quantity: 7, options: { Size: '37', Color: 'Red' } },
      { id: 'var_018_38_red', title: '38 / Red', prices: [{ amount: 9999 }], inventory_quantity: 5, options: { Size: '38', Color: 'Red' } },
    ],
    collection: { id: 'col_07', title: 'Shoes', handle: 'shoes' },
    tags: [{ id: 'tag_12', value: 'featured' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_019',
    title: 'White Leather Sneakers',
    description: 'Minimalist white leather sneakers. Trendy platform sole, super comfortable.',
    handle: 'white-leather-sneakers',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600' }],
    price: { amount: 8999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['35', '36', '37', '38', '39', '40', '41', '42'] },
    ],
    variants: [
      { id: 'var_019_35', title: '35', prices: [{ amount: 8999 }], inventory_quantity: 10, options: { Size: '35' } },
      { id: 'var_019_36', title: '36', prices: [{ amount: 8999 }], inventory_quantity: 15, options: { Size: '36' } },
      { id: 'var_019_37', title: '37', prices: [{ amount: 8999 }], inventory_quantity: 15, options: { Size: '37' } },
      { id: 'var_019_38', title: '38', prices: [{ amount: 8999 }], inventory_quantity: 15, options: { Size: '38' } },
      { id: 'var_019_39', title: '39', prices: [{ amount: 8999 }], inventory_quantity: 5, options: { Size: '39' } },
    ],
    collection: { id: 'col_07', title: 'Shoes', handle: 'shoes' },
    tags: [{ id: 'tag_13', value: 'bestseller' }],
    created_at: new Date().toISOString(),
  },

  // Accessories
  {
    id: 'prod_021',
    title: 'Statement Gold Necklace',
    description: 'Bold layered gold necklace set. Hypoallergenic, tarnish-resistant finish.',
    handle: 'statement-gold-necklace',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600' }],
    price: { amount: 4999, currency_code: 'ngn' },
    options: [
      { name: 'Style', values: ['Layered', 'Single Chain', 'Choker'] },
    ],
    variants: [
      { id: 'var_021_layered', title: 'Layered', prices: [{ amount: 4999 }], inventory_quantity: 30, options: { Style: 'Layered' } },
      { id: 'var_021_single', title: 'Single Chain', prices: [{ amount: 3999 }], inventory_quantity: 30, options: { Style: 'Single Chain' } },
      { id: 'var_021_choker', title: 'Choker', prices: [{ amount: 2999 }], inventory_quantity: 25, options: { Style: 'Choker' } },
    ],
    collection: { id: 'col_08', title: 'Accessories', handle: 'accessories' },
    tags: [{ id: 'tag_14', value: 'bestseller' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_022',
    title: 'Luxury Silk Scarf',
    description: '100% pure silk scarf with hand-rolled edges. Versatile accessory for any outfit.',
    handle: 'luxury-silk-scarf',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600' }],
    price: { amount: 6999, currency_code: 'ngn' },
    options: [
      { name: 'Design', values: ['Floral', 'Geometric', 'Paisley', 'Solid'] },
    ],
    variants: [
      { id: 'var_022_floral', title: 'Floral', prices: [{ amount: 6999 }], inventory_quantity: 20, options: { Design: 'Floral' } },
      { id: 'var_022_geometric', title: 'Geometric', prices: [{ amount: 6999 }], inventory_quantity: 20, options: { Design: 'Geometric' } },
      { id: 'var_022_paisley', title: 'Paisley', prices: [{ amount: 7499 }], inventory_quantity: 15, options: { Design: 'Paisley' } },
      { id: 'var_022_solid', title: 'Solid', prices: [{ amount: 5999 }], inventory_quantity: 10, options: { Design: 'Solid' } },
    ],
    collection: { id: 'col_08', title: 'Accessories', handle: 'accessories' },
    tags: [{ id: 'tag_15', value: 'featured' }],
    created_at: new Date().toISOString(),
  },

  // Perfumes
  {
    id: 'prod_024',
    title: 'Royal Oud EDP',
    description: 'Luxurious oriental fragrance with oud, amber, and sandalwood. Long-lasting 12+ hours.',
    handle: 'royal-oud-edp',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600' }],
    price: { amount: 19999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['50ml', '100ml'] },
    ],
    variants: [
      { id: 'var_024_50ml', title: '50ml', prices: [{ amount: 12999 }], inventory_quantity: 20, options: { Size: '50ml' } },
      { id: 'var_024_100ml', title: '100ml', prices: [{ amount: 19999 }], inventory_quantity: 20, options: { Size: '100ml' } },
    ],
    collection: { id: 'col_09', title: 'Perfumes', handle: 'perfumes' },
    tags: [{ id: 'tag_16', value: 'featured' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_025',
    title: 'Floral Essence Body Mist',
    description: 'Light refreshing body mist with rose and jasmine. Perfect for everyday wear.',
    handle: 'floral-essence-body-mist',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600' }],
    price: { amount: 2999, currency_code: 'ngn' },
    options: [
      { name: 'Size', values: ['50ml', '100ml', '150ml'] },
    ],
    variants: [
      { id: 'var_025_50ml', title: '50ml', prices: [{ amount: 1999 }], inventory_quantity: 50, options: { Size: '50ml' } },
      { id: 'var_025_100ml', title: '100ml', prices: [{ amount: 2999 }], inventory_quantity: 50, options: { Size: '100ml' } },
      { id: 'var_025_150ml', title: '150ml', prices: [{ amount: 3999 }], inventory_quantity: 50, options: { Size: '150ml' } },
    ],
    collection: { id: 'col_09', title: 'Perfumes', handle: 'perfumes' },
    tags: [{ id: 'tag_17', value: 'bestseller' }],
    created_at: new Date().toISOString(),
  },

  // Gift Items
  {
    id: 'prod_027',
    title: 'Luxury Gift Box Set',
    description: 'Premium gift box with skincare trio, bath bomb, and scented candle. Beautifully packaged.',
    handle: 'luxury-gift-box-set',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=600' }],
    price: { amount: 7999, currency_code: 'ngn' },
    options: [
      { name: 'Theme', values: ['Spa Day', 'Romantic', 'Self Care', 'Birthday'] },
    ],
    variants: [
      { id: 'var_027_spa', title: 'Spa Day', prices: [{ amount: 7999 }], inventory_quantity: 20, options: { Theme: 'Spa Day' } },
      { id: 'var_027_romantic', title: 'Romantic', prices: [{ amount: 7999 }], inventory_quantity: 20, options: { Theme: 'Romantic' } },
      { id: 'var_027_selfcare', title: 'Self Care', prices: [{ amount: 7999 }], inventory_quantity: 15, options: { Theme: 'Self Care' } },
      { id: 'var_027_birthday', title: 'Birthday', prices: [{ amount: 8999 }], inventory_quantity: 5, options: { Theme: 'Birthday' } },
    ],
    collection: { id: 'col_10', title: 'Gift Items', handle: 'gift-items' },
    tags: [{ id: 'tag_18', value: 'featured' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod_030',
    title: 'Luxury Candle Gift Set',
    description: 'Set of 3 soy wax candles in signature scents. Long-lasting 50+ hours each.',
    handle: 'luxury-candle-gift-set',
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600',
    images: [{ url: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600' }],
    price: { amount: 4499, currency_code: 'ngn' },
    options: [
      { name: 'Scents', values: ['Vanilla & Amber', 'Lavender & Sage', 'Rose & Sandalwood'] },
    ],
    variants: [
      { id: 'var_030_vanilla', title: 'Vanilla & Amber', prices: [{ amount: 4499 }], inventory_quantity: 30, options: { Scents: 'Vanilla & Amber' } },
      { id: 'var_030_lavender', title: 'Lavender & Sage', prices: [{ amount: 4499 }], inventory_quantity: 30, options: { Scents: 'Lavender & Sage' } },
      { id: 'var_030_rose', title: 'Rose & Sandalwood', prices: [{ amount: 4499 }], inventory_quantity: 35, options: { Scents: 'Rose & Sandalwood' } },
    ],
    collection: { id: 'col_10', title: 'Gift Items', handle: 'gift-items' },
    tags: [],
    created_at: new Date().toISOString(),
  },
];

export async function GET() {
  return NextResponse.json({
    products,
    count: products.length,
  });
}
