require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Product = require('../models/Product');

const slugify = (name) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const products = [
  // ── JACKETS & BLAZERS ──────────────────────────────────────────────────
  {
    sku: '219201531110',
    name: 'Black Fashion Jean Jacket',
    description: 'A versatile and effortlessly cool black denim jacket for the modern woman. Features a classic fit with button closure, making it a wardrobe essential that pairs perfectly with any outfit — from casual denim looks to elevated evening ensembles.',
    subcategory: 'Jackets & Blazers',
    price: 55000, costPrice: 55000, stock: 1,
    tags: ['jacket', 'denim', 'black', 'casual', 'fashion', 'womens'],
  },
  {
    sku: '219201331110',
    name: 'Navy Blue Long Miss You Jacket Size 38-46',
    description: 'A sophisticated long jacket in rich navy blue, cut to flatter sizes 38 to 46. The Miss You silhouette features clean lines, structured shoulders, and a refined finish that transitions effortlessly from office to evening wear.',
    subcategory: 'Jackets & Blazers',
    price: 125000, costPrice: 125000, stock: 4,
    tags: ['jacket', 'navy blue', 'long', 'structured', 'womens', 'plus size'],
  },
  {
    sku: '219201361110',
    name: 'Green Long Miss You Jacket Size 38-46',
    description: 'Make a bold statement in this striking green long jacket from the Miss You collection. Tailored to fit sizes 38 to 46, its structured cut and vibrant hue give it a commanding yet feminine presence — ideal for power dressing.',
    subcategory: 'Jackets & Blazers',
    price: 125000, costPrice: 125000, stock: 5,
    tags: ['jacket', 'green', 'long', 'structured', 'womens', 'plus size'],
  },
  {
    sku: '219201351110',
    name: 'Red Long Miss You Jacket Size 38-46',
    description: 'Confidence personified in this fiery red long jacket from the Miss You collection. Expertly cut for sizes 38 to 46 with a tailored silhouette that commands attention. Pair over a dress or coordinated trousers for an unforgettable look.',
    subcategory: 'Jackets & Blazers',
    price: 125000, costPrice: 125000, stock: 5,
    tags: ['jacket', 'red', 'long', 'structured', 'womens', 'plus size'],
  },
  {
    sku: '219201341110',
    name: 'Black Long Miss You Jacket Size 38-46',
    description: 'A wardrobe cornerstone: the Miss You long black jacket. Timeless, versatile, and impeccably structured across sizes 38 to 46. Its sleek silhouette and clean finish make it the perfect anchor piece for both formal and smart-casual outfits.',
    subcategory: 'Jackets & Blazers',
    price: 125000, costPrice: 125000, stock: 5,
    tags: ['jacket', 'black', 'long', 'structured', 'womens', 'plus size'],
  },
  {
    sku: '219201421110',
    name: 'Black John Roberts Jacket Size S',
    description: 'A chic and polished black jacket by John Roberts, tailored for a size S frame. Its refined construction, neat collar, and clean closure make it a go-to piece for smart casual and formal occasions alike.',
    subcategory: 'Jackets & Blazers',
    price: 75000, costPrice: 75000, stock: 1,
    tags: ['jacket', 'black', 'john roberts', 'designer', 'womens', 'size s'],
  },
  {
    sku: '219204611100',
    name: 'Black Adele Jean Zipper Jacket Size M',
    description: 'A sleek and edgy denim jacket in black by Adele, featuring a modern zipper closure for a contemporary finish. The medium size offers a fitted silhouette that pairs effortlessly with jeans, skirts, or dresses for a cool, casual aesthetic.',
    subcategory: 'Jackets & Blazers',
    price: 65000, costPrice: 65000, stock: 2,
    tags: ['jacket', 'denim', 'black', 'adele', 'zipper', 'casual', 'size m'],
  },
  {
    sku: '219204711102',
    name: 'Black Adele Jean Zipper Jacket Size L',
    description: 'The Adele black denim zipper jacket in size large delivers the perfect blend of edge and ease. Its zipper detail and fitted cut make it a standout layering piece over any outfit, from casual tees to flowy dresses.',
    subcategory: 'Jackets & Blazers',
    price: 65000, costPrice: 65000, stock: 2,
    tags: ['jacket', 'denim', 'black', 'adele', 'zipper', 'casual', 'size l'],
  },
  {
    sku: '219204811104',
    name: 'Black Adele Jean Zipper Jacket Size XL',
    description: 'Adele denim zipper jacket in size XL — a bold, structured outerwear piece in black that zips up for a clean, modern look. Versatile enough for everyday styling yet sharp enough to elevate any outfit.',
    subcategory: 'Jackets & Blazers',
    price: 65000, costPrice: 65000, stock: 3,
    tags: ['jacket', 'denim', 'black', 'adele', 'zipper', 'casual', 'size xl'],
  },
  {
    sku: '219202611108',
    name: 'Atmosphere Drop Tube Jacket Size S',
    description: 'A unique and fashion-forward tube jacket from Atmosphere, designed for a size S frame. Its drop silhouette and unconventional structure make it a conversation piece — perfect for the style-conscious woman who loves to stand out.',
    subcategory: 'Jackets & Blazers',
    price: 50000, costPrice: 50000, stock: 1,
    tags: ['jacket', 'atmosphere', 'tube', 'fashion', 'womens', 'size s'],
  },
  {
    sku: '219204211109',
    name: 'Finelong Navy Blue Blazer Pearl Button L XL 2XL',
    description: 'An elegant and polished blazer by Finelong in rich navy blue, adorned with lustrous pearl buttons for a feminine and sophisticated touch. Available in sizes L to 2XL with a structured silhouette that flatters and commands attention.',
    subcategory: 'Jackets & Blazers',
    price: 65000, costPrice: 65000, stock: 2,
    tags: ['blazer', 'navy blue', 'finelong', 'pearl button', 'structured', 'womens'],
  },
  {
    sku: '219204111107',
    name: 'Finelong Peach & Black Collar Blazer Size M',
    description: 'A chic two-tone blazer by Finelong featuring a peach body with contrasting black collar detailing. This size M blazer brings a fresh, fashion-forward energy to any look, whether styled with tailored trousers or a pencil skirt.',
    subcategory: 'Jackets & Blazers',
    price: 65000, costPrice: 65000, stock: 1,
    tags: ['blazer', 'peach', 'black', 'finelong', 'collar', 'womens', 'size m'],
  },
  {
    sku: '219204011103',
    name: 'Finelong Black Crop Blazer Stoned Collar M L XL',
    description: 'Make a statement in this stunning Finelong crop blazer in black with an eye-catching stoned collar. The cropped silhouette adds a modern edge, while the stone embellishments elevate it to evening-worthy glamour. Available in M, L, and XL.',
    subcategory: 'Jackets & Blazers',
    price: 55000, costPrice: 55000, stock: 4,
    tags: ['blazer', 'black', 'crop', 'finelong', 'stoned', 'embellished', 'womens'],
  },
  // ── SKIRTS ─────────────────────────────────────────────────────────────
  {
    sku: '219201524110',
    name: 'Giorgio Giulini Chinese Royal Pleated Skirt Black',
    description: 'An exquisite pleated skirt by Giorgio Giulini, inspired by Chinese royalty. The black colorway lends it timeless elegance — rich pleating cascades from the waist for a dramatic and regal silhouette that commands the room.',
    subcategory: 'Skirts',
    price: 85000, costPrice: 85000, stock: 1,
    tags: ['skirt', 'pleated', 'giorgio giulini', 'black', 'chinese royal', 'elegant', 'designer'],
  },
  {
    sku: '219201523110',
    name: 'Giorgio Giulini Chinese Royal Pleated Skirt Green',
    description: 'The Giorgio Giulini Chinese Royal Pleated Skirt in a vibrant green is a masterwork of structured elegance. Flowing pleats create movement and drama, while the bold green hue makes it a stunning statement piece for formal occasions.',
    subcategory: 'Skirts',
    price: 205000, costPrice: 205000, stock: 1,
    tags: ['skirt', 'pleated', 'giorgio giulini', 'green', 'chinese royal', 'elegant', 'designer'],
  },
  {
    sku: '219201522110',
    name: 'Giorgio Giulini Chinese Royal Pleated Skirt Red',
    description: 'Drama and opulence in one piece — the Giorgio Giulini Chinese Royal Pleated Skirt in red. The bold hue paired with meticulously crafted pleating creates an unforgettable silhouette worthy of the grandest occasions.',
    subcategory: 'Skirts',
    price: 205000, costPrice: 205000, stock: 1,
    tags: ['skirt', 'pleated', 'giorgio giulini', 'red', 'chinese royal', 'elegant', 'designer'],
  },
  {
    sku: '219201521110',
    name: 'Giorgio Giulini Chinese Royal Pleated Skirt Pink',
    description: 'Feminine and breathtaking, this pink Giorgio Giulini Chinese Royal Pleated Skirt blends Eastern-inspired design with high fashion. The delicate pink tone softens the structured pleats for a look that is both romantic and powerful.',
    subcategory: 'Skirts',
    price: 205000, costPrice: 205000, stock: 2,
    tags: ['skirt', 'pleated', 'giorgio giulini', 'pink', 'chinese royal', 'elegant', 'designer'],
  },
  {
    sku: '219206411106',
    name: 'Giorgio Giulini Chinese Royal Pleated Skirt Light Blue',
    description: 'A serene and captivating light blue iteration of the iconic Giorgio Giulini Chinese Royal Pleated Skirt. The soft blue hue flows through structured pleats for an airy, almost ethereal silhouette that turns heads at every step.',
    subcategory: 'Skirts',
    price: 205000, costPrice: 205000, stock: 2,
    tags: ['skirt', 'pleated', 'giorgio giulini', 'light blue', 'chinese royal', 'elegant', 'designer'],
  },
  {
    sku: '219206111100',
    name: 'Giorgio Giulini Chinese Royal Pleated Skirt Black Signature',
    description: 'The signature black edition of the Giorgio Giulini Chinese Royal Pleated Skirt — a bold, architectural masterpiece. With deep pleats and impeccable drape, this black skirt is the definitive choice for women who dress with intention.',
    subcategory: 'Skirts',
    price: 205000, costPrice: 205000, stock: 5,
    tags: ['skirt', 'pleated', 'giorgio giulini', 'black', 'chinese royal', 'elegant', 'designer'],
  },
  {
    sku: '219206311107',
    name: 'Giorgio Giulini Chinese Royal Pleated Skirt Lemon',
    description: 'Bright, fresh, and utterly elegant — the Giorgio Giulini Chinese Royal Pleated Skirt in lemon yellow radiates sunshine and sophistication. The striking color paired with royal pleating creates a look that is both playful and high fashion.',
    subcategory: 'Skirts',
    price: 205000, costPrice: 205000, stock: 1,
    tags: ['skirt', 'pleated', 'giorgio giulini', 'lemon', 'yellow', 'chinese royal', 'designer'],
  },
  {
    sku: '219201501110',
    name: 'Giorgio Flair Skirt',
    description: 'A beautifully fluid flair skirt in the Giorgio style. The flared silhouette moves gracefully with every step, offering a feminine and flattering shape that works from brunch to evening events.',
    subcategory: 'Skirts',
    price: 55000, costPrice: 55000, stock: 4,
    tags: ['skirt', 'flair', 'flared', 'giorgio', 'feminine', 'womens'],
  },
  {
    sku: '219207011105',
    name: 'Black Skirt With Short',
    description: 'A modern and versatile black skirt with a built-in short, giving you confidence and coverage all in one. Its sleek design and comfortable layered construction make it perfect for active styling or chic everyday wear.',
    subcategory: 'Skirts',
    price: 48500, costPrice: 48500, stock: 1,
    tags: ['skirt', 'black', 'shorts', 'layered', 'casual', 'womens'],
  },
  {
    sku: '219203711106',
    name: 'Princess Palazzo Pant Dark Brown Size 40-46',
    description: 'Elegant and flowing, these Princess Palazzo trousers in dark brown are the epitome of relaxed sophistication. Wide-leg and comfortable across sizes 40 to 46, they pair beautifully with fitted tops or blouses for a polished ensemble.',
    subcategory: 'Skirts',
    price: 65000, costPrice: 65000, stock: 1,
    tags: ['palazzo', 'trousers', 'dark brown', 'wide leg', 'princess', 'womens', 'plus size'],
  },
  {
    sku: '219203511100',
    name: 'Fusion Carton Color 3/4 Skirt & Belt Size 36-42',
    description: 'A fun and fashion-forward 3/4-length skirt by Fusion in a playful carton print, complete with a matching belt. Available in sizes 36 to 42, it creates a polished waist-defining look with a creative, artistic flair.',
    subcategory: 'Skirts',
    price: 70000, costPrice: 70000, stock: 3,
    tags: ['skirt', 'belt', 'fusion', 'carton print', '3/4', 'colorful', 'womens'],
  },
  {
    sku: '219203111108',
    name: 'Fusion Brown Skirt & Belt UK 12',
    description: 'A refined brown skirt from Fusion, paired with a complementary belt for a cinched, flattering finish. Sized UK 12, it offers a tailored silhouette that works across both casual and smart-casual settings.',
    subcategory: 'Skirts',
    price: 65000, costPrice: 65000, stock: 1,
    tags: ['skirt', 'belt', 'fusion', 'brown', 'uk 12', 'tailored', 'womens'],
  },
  {
    sku: '219203011106',
    name: 'Exit Line Snake Skin 2-Piece Skirt Set Size 40-48',
    description: 'An fierce and sophisticated snake skin-print 2-piece skirt set by Exit Line. Available in sizes 40 to 48, the bold animal print and coordinated matching set make it a standout choice for women who love to make a statement.',
    subcategory: 'Skirts',
    price: 120000, costPrice: 120000, stock: 4,
    tags: ['skirt', 'set', 'snake skin', 'exit line', 'animal print', 'womens', 'plus size'],
  },
  {
    sku: '219203311108',
    name: 'Fusion Black Leather Skirt & Short UK 14',
    description: 'Edge meets femininity in this Fusion black leather skirt with built-in shorts, sized UK 14. Its sleek leather construction gives it a bold, contemporary look that transitions seamlessly from day to night.',
    subcategory: 'Skirts',
    price: 60000, costPrice: 60000, stock: 1,
    tags: ['skirt', 'leather', 'black', 'fusion', 'shorts', 'edgy', 'uk 14'],
  },
  {
    sku: '219203211102',
    name: 'Fusion Pink & Blue Striped Lace Skirt UK 10-14',
    description: 'A delightfully feminine pink and blue striped lace skirt from Fusion. Available in UK 10 and UK 14, its delicate lace construction and playful stripe pattern create a romantic, flirty aesthetic perfect for daytime occasions.',
    subcategory: 'Skirts',
    price: 65000, costPrice: 65000, stock: 2,
    tags: ['skirt', 'lace', 'striped', 'pink', 'blue', 'fusion', 'feminine', 'womens'],
  },
  {
    sku: '219205911108',
    name: 'Francesca Mesh Skirt',
    description: 'The Francesca Mesh Skirt is a sheer, ethereal piece that adds lightness and allure to any outfit. Its delicate mesh construction creates a dreamy, layered look, perfect for styling over a slip or coordinated bodysuit for a bold fashion statement.',
    subcategory: 'Skirts',
    price: 90000, costPrice: 90000, stock: 1,
    tags: ['skirt', 'mesh', 'francesca', 'sheer', 'layered', 'fashion', 'womens'],
  },
  {
    sku: '219205511101',
    name: 'Amber Sky Flowery Skirt S M',
    description: 'A light, romantic floral skirt in warm amber tones, available in sizes S and M. The Amber Sky design features delicate flower prints across a flowing, easy-wearing silhouette — effortlessly feminine for weekend outings and garden parties.',
    subcategory: 'Skirts',
    price: 45000, costPrice: 45000, stock: 2,
    tags: ['skirt', 'floral', 'amber', 'flowery', 'feminine', 'casual', 'womens'],
  },
  // ── GOWNS & DRESSES ────────────────────────────────────────────────────
  {
    sku: '219201041110',
    name: 'Red AIO Free Gown',
    description: 'A vibrant and free-spirited all-in-one red gown with a relaxed, flattering silhouette. Its bold color and comfortable free-size design make it an ideal choice for casual outings, beach days, or effortless everyday style.',
    subcategory: 'Gowns & Dresses',
    price: 75000, costPrice: 75000, stock: 2,
    tags: ['gown', 'red', 'free size', 'casual', 'all-in-one', 'womens'],
  },
  {
    sku: '219201511110',
    name: 'Short Lacey Dress',
    description: 'A beautifully crafted short lace dress that exudes femininity and romance. The delicate lacework adds texture and elegance to this versatile piece, making it a perfect choice for date nights, cocktail parties, or evening outings.',
    subcategory: 'Gowns & Dresses',
    price: 75000, costPrice: 75000, stock: 10,
    tags: ['dress', 'lace', 'short', 'feminine', 'elegant', 'cocktail', 'womens'],
  },
  {
    sku: '219201261110',
    name: 'Pink Gown With Round Stone Design',
    description: 'An enchanting pink gown adorned with beautiful round stone embellishments that catch the light with every movement. Its romantic hue and sparkling detailing make it an unforgettable choice for special occasions and evening events.',
    subcategory: 'Gowns & Dresses',
    price: 95000, costPrice: 95000, stock: 2,
    tags: ['gown', 'pink', 'stones', 'embellished', 'evening', 'special occasion', 'womens'],
  },
  {
    sku: '219201481110',
    name: 'Free Assemble Gown',
    description: 'A versatile and effortless gown with a free-form assembly that allows for a variety of styling options. Its relaxed construction flatters multiple body types, making it an adaptable wardrobe staple for both casual and semi-formal settings.',
    subcategory: 'Gowns & Dresses',
    price: 60000, costPrice: 60000, stock: 2,
    tags: ['gown', 'free size', 'versatile', 'casual', 'womens'],
  },
  {
    sku: '219201411110',
    name: 'Pink Jumpsuit Shelby & Palmer Size L',
    description: 'A stylish and flattering pink jumpsuit by Shelby & Palmer in size L. Its sleek silhouette and rose-hued construction make it a chic one-piece option for brunches, events, or elevated casual wear.',
    subcategory: 'Gowns & Dresses',
    price: 85000, costPrice: 85000, stock: 1,
    tags: ['jumpsuit', 'pink', 'shelby & palmer', 'womens', 'one-piece', 'size l'],
  },
  {
    sku: '219201221110',
    name: 'Black Sleeveless Big Stoned & Slit Gown',
    description: 'A head-turning black sleeveless gown featuring bold stone embellishments and a daring thigh-high slit. Glamorous and commanding, this gown is designed for the woman who walks into a room and owns it.',
    subcategory: 'Gowns & Dresses',
    price: 115000, costPrice: 115000, stock: 3,
    tags: ['gown', 'black', 'stones', 'slit', 'sleeveless', 'glamour', 'evening', 'womens'],
  },
  {
    sku: '219201141110',
    name: 'Black Short Gown With Blue Stones',
    description: 'A striking black short gown embellished with vibrant blue stones that add a pop of color and glamour. Its minilength silhouette and bold stone detailing make it a dazzling choice for parties and evening events.',
    subcategory: 'Gowns & Dresses',
    price: 145000, costPrice: 145000, stock: 1,
    tags: ['gown', 'black', 'blue stones', 'short', 'embellished', 'glamour', 'womens'],
  },
  {
    sku: '219201311110',
    name: 'Red Short Gown With Stones',
    description: 'A fiery and glamorous red short gown adorned with sparkling stone embellishments. Dramatic, bold, and utterly captivating — this gown is the perfect choice for galas, nightclubs, or any occasion where you want to be remembered.',
    subcategory: 'Gowns & Dresses',
    price: 145000, costPrice: 145000, stock: 3,
    tags: ['gown', 'red', 'stones', 'short', 'embellished', 'glamour', 'evening', 'womens'],
  },
  {
    sku: '219201291110',
    name: 'Black Transparent Stoned Gown',
    description: 'Daring and breathtaking, this black transparent stoned gown is a masterpiece of sensuality and elegance. The sheer body is adorned with intricate stone placements that provide coverage and artistry, creating an unforgettable red-carpet look.',
    subcategory: 'Gowns & Dresses',
    price: 185000, costPrice: 185000, stock: 1,
    tags: ['gown', 'black', 'transparent', 'sheer', 'stones', 'red carpet', 'luxury', 'womens'],
  },
  {
    sku: '219201281110',
    name: 'Black & Red Rose Mono Strap Gown',
    description: 'A romantically dramatic mono-strap gown featuring a black and red rose design. The single-shoulder silhouette adds a touch of asymmetric elegance, while the floral motif brings beauty and femininity to this showstopping piece.',
    subcategory: 'Gowns & Dresses',
    price: 145000, costPrice: 145000, stock: 3,
    tags: ['gown', 'black', 'red', 'rose', 'mono strap', 'floral', 'glamour', 'womens'],
  },
  {
    sku: '219201271110',
    name: 'Green Gown With Round Stoned Design',
    description: 'An enchanting green gown adorned with a beautiful round stone design that adds sparkle and dimension. The vibrant green hue and embellished detailing combine to create a stunning, nature-inspired evening look full of life and glamour.',
    subcategory: 'Gowns & Dresses',
    price: 95000, costPrice: 95000, stock: 3,
    tags: ['gown', 'green', 'stones', 'embellished', 'evening', 'special occasion', 'womens'],
  },
  {
    sku: '219201251110',
    name: 'Red Gown With Round Stones Design',
    description: 'A passionate red gown embellished with intricate round stone detailing across its silhouette. Every movement catches the light, making this gown an irresistible choice for grand events, weddings, and celebratory occasions.',
    subcategory: 'Gowns & Dresses',
    price: 95000, costPrice: 95000, stock: 3,
    tags: ['gown', 'red', 'stones', 'embellished', 'evening', 'special occasion', 'womens'],
  },
  {
    sku: '219201241110',
    name: 'Silver Gown With Crenelum',
    description: 'A breathtaking silver gown featuring a unique crenelum structural detail that adds architectural drama and luxury. Its metallic shimmer and bold construction make it an extraordinary choice for fashion-forward women at high-profile events.',
    subcategory: 'Gowns & Dresses',
    price: 135000, costPrice: 135000, stock: 1,
    tags: ['gown', 'silver', 'metallic', 'structured', 'luxury', 'special occasion', 'womens'],
  },
  {
    sku: '219201211110',
    name: 'Black Suede Gold Chain Design Gown With Gloves',
    description: 'Opulence redefined — this black suede gown features bold gold chain embellishments and comes complete with matching gloves. A full luxury fashion moment, it is designed for the woman who makes every entrance a statement.',
    subcategory: 'Gowns & Dresses',
    price: 180000, costPrice: 180000, stock: 2,
    tags: ['gown', 'black', 'suede', 'gold chain', 'gloves', 'luxury', 'glamour', 'womens'],
  },
  {
    sku: '219201201110',
    name: 'White Rose Halter Neck Gown',
    description: 'Effortlessly romantic, this white halter neck gown is adorned with delicate rose detailing. The halter silhouette showcases the shoulders and neckline beautifully, while the white rose motif adds a timeless, bridal-inspired elegance.',
    subcategory: 'Gowns & Dresses',
    price: 115000, costPrice: 115000, stock: 1,
    tags: ['gown', 'white', 'rose', 'halter neck', 'romantic', 'elegant', 'womens'],
  },
  {
    sku: '219201191110',
    name: 'Red Rose Halter Neck Gown',
    description: 'A passionate and seductive red halter neck gown adorned with beautiful rose details. The bold color and open-back halter design create a combination of strength and femininity that is impossible to ignore.',
    subcategory: 'Gowns & Dresses',
    price: 115000, costPrice: 115000, stock: 2,
    tags: ['gown', 'red', 'rose', 'halter neck', 'romantic', 'sensual', 'womens'],
  },
  {
    sku: '219201181110',
    name: 'Black Rose Halter Neck Gown',
    description: 'Mysterious and alluring, this black halter neck gown features stunning rose embellishment. The dark elegance of the black rose design combined with the sleek halter silhouette creates a look of sophisticated sensuality perfect for evening wear.',
    subcategory: 'Gowns & Dresses',
    price: 115000, costPrice: 115000, stock: 1,
    tags: ['gown', 'black', 'rose', 'halter neck', 'elegant', 'sensual', 'womens'],
  },
  {
    sku: '219201171110',
    name: 'White Sleeveless Turtle Neck Gown',
    description: 'A sleek and modern white sleeveless turtleneck gown that blends minimalist elegance with bold structure. The high neck contrasted with bare arms creates a chic, editorial look suitable for sophisticated events and formal dinners.',
    subcategory: 'Gowns & Dresses',
    price: 125000, costPrice: 125000, stock: 2,
    tags: ['gown', 'white', 'turtleneck', 'sleeveless', 'minimalist', 'elegant', 'womens'],
  },
  {
    sku: '219201161110',
    name: 'Red Sleeveless Turtle Neck Gown',
    description: 'A bold and striking red sleeveless turtleneck gown that makes an unforgettable statement. The combination of high-neck drama and bare-shoulder confidence creates a look that is simultaneously powerful and incredibly chic.',
    subcategory: 'Gowns & Dresses',
    price: 125000, costPrice: 125000, stock: 1,
    tags: ['gown', 'red', 'turtleneck', 'sleeveless', 'bold', 'elegant', 'womens'],
  },
  {
    sku: '219201151110',
    name: 'Black Sleeveless Turtle Neck Gown',
    description: 'Timeless and powerful, this black sleeveless turtleneck gown is the ultimate in modern elegance. Its structured silhouette, high neck, and bare arms create a stunning contrast that works beautifully for high-end events and formal occasions.',
    subcategory: 'Gowns & Dresses',
    price: 125000, costPrice: 125000, stock: 3,
    tags: ['gown', 'black', 'turtleneck', 'sleeveless', 'minimalist', 'elegant', 'womens'],
  },
  {
    sku: '219201031110',
    name: 'Brown CK Long Maxi Gown',
    description: 'A luxurious and relaxed long maxi gown by CK in a rich warm brown. The flowing silhouette and quality fabric drape beautifully for a look that is effortlessly sophisticated — ideal for casual luxury or smart casual events.',
    subcategory: 'Gowns & Dresses',
    price: 75000, costPrice: 75000, stock: 2,
    tags: ['gown', 'brown', 'ck', 'calvin klein', 'maxi', 'long', 'casual', 'womens'],
  },
  {
    sku: '219205711108',
    name: 'Bar III Silver Shiny Short Gown Size S',
    description: 'A dazzling silver mini dress by Bar III that shimmers with every movement. Its metallic sheen and body-skimming silhouette make it the definitive choice for nights out, cocktail parties, and any occasion demanding a touch of brilliance.',
    subcategory: 'Gowns & Dresses',
    price: 85000, costPrice: 85000, stock: 1,
    tags: ['dress', 'silver', 'metallic', 'bar iii', 'short', 'shiny', 'party', 'size s'],
  },
  {
    sku: '219207411109',
    name: 'Pink Stoned Flare Gown',
    description: 'A whimsical and romantic pink flare gown adorned with sparkling stone embellishments. The flared silhouette moves beautifully and the stone details add a magical, fairytale quality that makes it perfect for special occasions.',
    subcategory: 'Gowns & Dresses',
    price: 55000, costPrice: 55000, stock: 1,
    tags: ['gown', 'pink', 'stones', 'flare', 'romantic', 'embellished', 'womens'],
  },
  {
    sku: '219206811102',
    name: 'Black Gown With Feathered Hands',
    description: 'An extraordinary black gown featuring dramatic feathered sleeve detailing that creates a bold, theatrical effect. Glamorous and memorable, this gown is for the woman who refuses to go unnoticed at any event.',
    subcategory: 'Gowns & Dresses',
    price: 55000, costPrice: 55000, stock: 1,
    tags: ['gown', 'black', 'feathers', 'dramatic', 'glamour', 'evening', 'womens'],
  },
  {
    sku: '219206511106',
    name: 'Bridal Gowns',
    description: 'Exquisite bridal gowns crafted for the most important day of your life. Each piece is thoughtfully designed with premium fabrics, elegant silhouettes, and fine detailing to ensure every bride feels as beautiful and special as she deserves.',
    subcategory: 'Gowns & Dresses',
    price: 850000, costPrice: 850000, stock: 6,
    tags: ['bridal', 'wedding gown', 'bride', 'luxury', 'special occasion', 'womens'],
  },
  {
    sku: '219205611108',
    name: 'Madden Girl Black Short Shimmer Gown Size S',
    description: 'A sleek and alluring short shimmer gown by Madden Girl in black, available in size S. Its body-conscious cut and subtle shimmer finish make it an ideal choice for nights out, celebrations, and cocktail events.',
    subcategory: 'Gowns & Dresses',
    price: 65000, costPrice: 65000, stock: 1,
    tags: ['dress', 'black', 'shimmer', 'madden girl', 'short', 'party', 'size s'],
  },
  {
    sku: '219202411107',
    name: 'Laulia Tube Jean Gown Blue Size 34',
    description: 'A form-fitting tube denim gown by Laulia in blue, sized 34. This chic jean gown combines the casual appeal of denim with a sophisticated tube silhouette, creating a unique and fashion-forward look perfect for trendy outings.',
    subcategory: 'Gowns & Dresses',
    price: 70000, costPrice: 70000, stock: 2,
    tags: ['gown', 'denim', 'tube', 'blue', 'laulia', 'jean', 'size 34', 'womens'],
  },
  {
    sku: '219202111102',
    name: 'Lavlia Faded Black Jean Tube Gown Size 34',
    description: 'An effortlessly cool faded black denim tube gown by Lavlia in size 34. The washed denim texture adds a lived-in, artistic edge to the tube silhouette — a perfect blend of casual cool and feminine confidence.',
    subcategory: 'Gowns & Dresses',
    price: 70000, costPrice: 70000, stock: 1,
    tags: ['gown', 'denim', 'tube', 'black', 'lavlia', 'faded', 'size 34', 'womens'],
  },
  // ── TOPS & SHIRTS ──────────────────────────────────────────────────────
  {
    sku: '219201111110',
    name: 'Short Sleeve Black Top M XL 2XL 3XL',
    description: 'A clean, versatile short-sleeve black top available from M to 3XL. A wardrobe essential that pairs with anything — from tailored trousers to casual jeans. Its comfortable fabric and simple design make it a go-to piece for everyday wear.',
    subcategory: 'Tops & Shirts',
    price: 45000, costPrice: 45000, stock: 4,
    tags: ['top', 'black', 'short sleeve', 'casual', 'womens', 'plus size'],
  },
  {
    sku: '219201121110',
    name: 'Short Sleeve Dark Brown Top M 2XL 3XL',
    description: 'A rich dark brown short-sleeve top with a warm, earthy tone that flatters a range of complexions. Available from M to 3XL, this versatile staple is easy to wear and style for any casual to smart-casual occasion.',
    subcategory: 'Tops & Shirts',
    price: 45000, costPrice: 45000, stock: 4,
    tags: ['top', 'dark brown', 'short sleeve', 'casual', 'womens', 'plus size'],
  },
  {
    sku: '219201131110',
    name: 'Short Sleeve Light Brown Top M 2XL 3XL',
    description: 'A warm and soft light brown short-sleeve top that pairs effortlessly with denim, skirts, or tailored pieces. Available in generous sizing from M to 3XL for a comfortable, relaxed fit that never compromises on style.',
    subcategory: 'Tops & Shirts',
    price: 45000, costPrice: 45000, stock: 5,
    tags: ['top', 'light brown', 'short sleeve', 'casual', 'womens', 'plus size'],
  },
  {
    sku: '219201471110',
    name: 'Elle Stretchy Top',
    description: 'A figure-flattering stretchy top by Elle that moves with your body for all-day comfort. Its flexible fabric and clean design make it ideal for layering or wearing solo, suitable for both workday ease and weekend outings.',
    subcategory: 'Tops & Shirts',
    price: 48500, costPrice: 48500, stock: 1,
    tags: ['top', 'elle', 'stretchy', 'comfortable', 'casual', 'womens'],
  },
  {
    sku: '219201461110',
    name: 'Black & White APT9 Top',
    description: 'A smart and versatile black and white top by APT.9 that transitions effortlessly from office to weekend. The monochrome design is clean and classic, making it a wardrobe staple that works with virtually any bottom.',
    subcategory: 'Tops & Shirts',
    price: 40000, costPrice: 40000, stock: 1,
    tags: ['top', 'black', 'white', 'apt9', 'monochrome', 'casual', 'womens'],
  },
  {
    sku: '219201451110',
    name: 'Animal Skin Cato Woman Top Size XL',
    description: 'A fierce and fashion-forward animal skin print top by Cato in size XL. The bold print adds instant personality to any outfit, whether paired with solid-color trousers or skirts for a look that is wild and confident.',
    subcategory: 'Tops & Shirts',
    price: 55000, costPrice: 55000, stock: 1,
    tags: ['top', 'animal print', 'cato', 'bold', 'size xl', 'womens'],
  },
  {
    sku: '219201441110',
    name: 'Multicolored Worthington Top Size M',
    description: 'A vibrant and expressive multicolored top by Worthington in size M. The bold color arrangement and quality fabrication make it a standout piece in any wardrobe — easy to style with neutral bottoms for a pop of personality.',
    subcategory: 'Tops & Shirts',
    price: 55000, costPrice: 55000, stock: 1,
    tags: ['top', 'multicolor', 'worthington', 'colorful', 'size m', 'womens'],
  },
  {
    sku: '219201431110',
    name: 'Sky Blue Long Sleeve Shirt With Collar Size XL',
    description: 'A fresh and polished sky blue long-sleeve shirt featuring a classic collar for a neat, refined look. Available in size XL, this clean and versatile shirt works for office environments, smart casual settings, and layered outfits.',
    subcategory: 'Tops & Shirts',
    price: 48500, costPrice: 48500, stock: 1,
    tags: ['shirt', 'sky blue', 'long sleeve', 'collar', 'size xl', 'smart casual', 'womens'],
  },
  {
    sku: '219201011110',
    name: 'Labubu Stones T-Shirt',
    description: 'A playful and trendy Labubu character t-shirt adorned with eye-catching stone embellishments. A fusion of streetwear culture and feminine sparkle, this tee is perfect for style-conscious women who love bold, expressive fashion.',
    subcategory: 'Tops & Shirts',
    price: 55000, costPrice: 55000, stock: 13,
    tags: ['t-shirt', 'labubu', 'stones', 'embellished', 'streetwear', 'trendy', 'womens'],
  },
  {
    sku: '219208511108',
    name: 'Lily Bianca Floral Top',
    description: 'A beautifully crafted floral top by Lily Bianca, featuring a delicate and feminine botanical print. Light, airy, and effortlessly stylish, it is the perfect piece for spring and summer styling, pairing beautifully with white jeans or skirts.',
    subcategory: 'Tops & Shirts',
    price: 55000, costPrice: 55000, stock: 3,
    tags: ['top', 'floral', 'lily bianca', 'feminine', 'spring', 'summer', 'womens'],
  },
  {
    sku: '219208411106',
    name: 'Lily Bianca Tiger Skin Brown Top',
    description: 'A bold and striking tiger skin print top by Lily Bianca in warm brown tones. The fierce animal print is balanced by the earthy brown palette for a look that is wild yet wearable — a true fashion statement for the daring woman.',
    subcategory: 'Tops & Shirts',
    price: 55000, costPrice: 55000, stock: 4,
    tags: ['top', 'tiger print', 'animal print', 'lily bianca', 'brown', 'bold', 'womens'],
  },
  {
    sku: '219203911104',
    name: 'Black Princess Top & Brooch Size 38-42',
    description: 'A regal and sophisticated black princess-cut top that comes with an elegant brooch accent. Available in sizes 38 to 42, its structured design and embellishment elevate this top to something truly special for formal and semi-formal events.',
    subcategory: 'Tops & Shirts',
    price: 55000, costPrice: 55000, stock: 1,
    tags: ['top', 'black', 'princess', 'brooch', 'formal', 'elegant', 'womens'],
  },
  {
    sku: '219203811101',
    name: 'Lemon Princess Top & Brooch Size 40-42',
    description: 'A bright and cheerful lemon-colored princess top with a matching brooch detail for sizes 40 to 42. The vibrant yellow tone and structured design create a look that is uplifting, polished, and perfect for daytime formal occasions.',
    subcategory: 'Tops & Shirts',
    price: 55000, costPrice: 55000, stock: 2,
    tags: ['top', 'lemon', 'yellow', 'princess', 'brooch', 'formal', 'elegant', 'womens'],
  },
  {
    sku: '219209911103',
    name: 'Rose T-Shirt',
    description: 'A charming rose-printed t-shirt that brings a touch of feminine floral energy to everyday wear. Easy to style and effortlessly pretty, it pairs perfectly with denim, joggers, or skirts for a casual look full of character.',
    subcategory: 'Tops & Shirts',
    price: 55000, costPrice: 55000, stock: 5,
    tags: ['t-shirt', 'rose', 'floral', 'casual', 'feminine', 'womens'],
  },
  {
    sku: '219201111091',
    name: 'Marco Donateli Animal Skin Shirt Size M',
    description: 'A bold and luxurious animal skin-print shirt by Marco Donateli in size M. The premium print and expert tailoring combine to create a distinctive piece that makes a powerful style statement — wear with solid bottoms to let it shine.',
    subcategory: 'Tops & Shirts',
    price: 50000, costPrice: 50000, stock: 1,
    tags: ['shirt', 'animal print', 'marco donateli', 'designer', 'bold', 'size m', 'womens'],
  },
  // ── JEANS & TROUSERS ───────────────────────────────────────────────────
  {
    sku: '219201491110',
    name: 'Blue Fashion Jean',
    description: 'A stylish and versatile blue fashion jean with a contemporary cut and clean finish. These denim trousers are a wardrobe essential that pairs with practically anything — from simple tops to blazers — for effortless everyday style.',
    subcategory: 'Jeans & Trousers',
    price: 85000, costPrice: 85000, stock: 9,
    tags: ['jeans', 'blue', 'denim', 'fashion', 'casual', 'womens'],
  },
  {
    sku: '219205111106',
    name: 'Blue Baggy Adele Jean Trouser Size XL',
    description: 'The Adele baggy jean trouser in blue, sized XL — a relaxed, wide-legged denim silhouette that is both comfortable and undeniably chic. Perfect for the modern woman who values ease without sacrificing style.',
    subcategory: 'Jeans & Trousers',
    price: 85000, costPrice: 85000, stock: 1,
    tags: ['jeans', 'baggy', 'blue', 'adele', 'wide leg', 'denim', 'size xl', 'womens'],
  },
  {
    sku: '219207711106',
    name: 'Black Fashion Jeans',
    description: 'A sleek and polished pair of black fashion jeans with a modern cut that flatters and elongates the figure. Versatile and timeless, these jeans transition seamlessly from day to night and pair with virtually any top in your wardrobe.',
    subcategory: 'Jeans & Trousers',
    price: 85000, costPrice: 85000, stock: 6,
    tags: ['jeans', 'black', 'denim', 'fashion', 'slim', 'womens'],
  },
  {
    sku: '219201001110',
    name: 'Denim Shorts With Gold Stone Design',
    description: 'Fashion-forward denim shorts embellished with a dazzling gold stone design for a glamorous edge. The combination of casual denim with luxurious stone detailing makes these shorts a unique and eye-catching addition to any summer wardrobe.',
    subcategory: 'Jeans & Trousers',
    price: 55000, costPrice: 55000, stock: 3,
    tags: ['shorts', 'denim', 'gold stones', 'embellished', 'summer', 'fashion', 'womens'],
  },
  {
    sku: '219207811105',
    name: 'Blue JK Ripped Jeans',
    description: 'A trend-forward pair of blue ripped jeans by JK with a relaxed, distressed finish for a cool, edgy aesthetic. The strategic rips and washes add personality to this wardrobe essential — a must-have for the fashion-conscious woman.',
    subcategory: 'Jeans & Trousers',
    price: 85000, costPrice: 85000, stock: 9,
    tags: ['jeans', 'blue', 'ripped', 'distressed', 'jk', 'edgy', 'casual', 'womens'],
  },
  {
    sku: '219205311100',
    name: 'Blue Augustinas Jean Trouser Size XL',
    description: 'Clean, tailored blue denim trousers by Augustinas in size XL. These well-cut jeans offer a polished straight-leg silhouette that can be dressed up with heels or dressed down with trainers for versatile everyday wear.',
    subcategory: 'Jeans & Trousers',
    price: 80000, costPrice: 80000, stock: 3,
    tags: ['jeans', 'blue', 'augustinas', 'tailored', 'size xl', 'denim', 'womens'],
  },
  {
    sku: '219204911107',
    name: 'Blue Baggy Adele Jean Trouser Size M',
    description: 'Adele baggy jean trouser in blue, size M — relaxed and roomy with a modern slouchy silhouette that leans into the oversized denim trend. Wear with a fitted crop top or a tucked-in shirt for an effortlessly cool look.',
    subcategory: 'Jeans & Trousers',
    price: 85000, costPrice: 85000, stock: 1,
    tags: ['jeans', 'baggy', 'blue', 'adele', 'wide leg', 'denim', 'size m', 'womens'],
  },
  {
    sku: '219205011105',
    name: 'Blue Baggy Adele Jean Trouser Size L',
    description: 'The Adele baggy denim trouser in blue, size L. With a generous wide-leg cut and comfortable waistband, these jeans deliver the relaxed elegance of oversized denim in a silhouette that flatters and flows with every movement.',
    subcategory: 'Jeans & Trousers',
    price: 85000, costPrice: 85000, stock: 3,
    tags: ['jeans', 'baggy', 'blue', 'adele', 'wide leg', 'denim', 'size l', 'womens'],
  },
  {
    sku: '219205211102',
    name: 'Blue Augustinas Jean Trouser Size L',
    description: 'Augustinas blue denim trousers in size L — a smartly cut pair of jeans with a clean finish and comfortable fit. Versatile and well-made, they are the kind of reliable denim that forms the backbone of any great wardrobe.',
    subcategory: 'Jeans & Trousers',
    price: 80000, costPrice: 80000, stock: 5,
    tags: ['jeans', 'blue', 'augustinas', 'tailored', 'size l', 'denim', 'womens'],
  },
  {
    sku: '219207611106',
    name: 'White & Multicolor Design Pant',
    description: 'A fresh and eye-catching white pant with a vibrant multicolor design that adds creative energy to any outfit. Lightweight and comfortable, it makes a bold color statement when paired with a simple white or neutral top.',
    subcategory: 'Jeans & Trousers',
    price: 45000, costPrice: 45000, stock: 1,
    tags: ['trousers', 'white', 'multicolor', 'print', 'casual', 'womens'],
  },
  {
    sku: '219207311109',
    name: 'Green Elastic Waist Pant',
    description: 'Comfortable and effortlessly stylish, these green elastic-waist trousers offer a relaxed fit with a polished appearance. The stretchy waistband ensures all-day comfort while the fresh green hue adds a pop of color to your wardrobe.',
    subcategory: 'Jeans & Trousers',
    price: 48500, costPrice: 48500, stock: 1,
    tags: ['trousers', 'green', 'elastic waist', 'comfortable', 'casual', 'womens'],
  },
  {
    sku: '219207211109',
    name: 'Blue Pant With Chain Detail',
    description: 'Fashion-forward blue trousers featuring a bold chain detail that adds an edgy, urban accent to the silhouette. The chain embellishment elevates these pants from simple to statement-making — wear with a sleek bodysuit to let them shine.',
    subcategory: 'Jeans & Trousers',
    price: 48500, costPrice: 48500, stock: 1,
    tags: ['trousers', 'blue', 'chain', 'embellished', 'edgy', 'fashion', 'womens'],
  },
  {
    sku: '219206911103',
    name: 'Leopard Print Pant',
    description: 'A fierce and timeless leopard print trouser that never goes out of style. The bold animal print adds instant character and confidence to any outfit — pair with a solid-color top and let these trousers do all the talking.',
    subcategory: 'Jeans & Trousers',
    price: 45000, costPrice: 45000, stock: 1,
    tags: ['trousers', 'leopard', 'animal print', 'bold', 'fashion', 'womens'],
  },
  {
    sku: '219206711107',
    name: 'Paper Print Pant',
    description: 'A creative and artistic paper print trouser that brings a graphic, editorial feel to your wardrobe. The unique print makes these trousers a conversation piece — wear with a minimalist top to let the bold pattern take center stage.',
    subcategory: 'Jeans & Trousers',
    price: 48500, costPrice: 48500, stock: 3,
    tags: ['trousers', 'print', 'graphic', 'artistic', 'fashion', 'womens'],
  },
  {
    sku: '219202711102',
    name: 'Blue Jean Shorts With Alphabet Stones',
    description: 'Trendy blue denim shorts embellished with alphabet stone detailing for a playful and personalized look. A fun, fashion-forward piece that is perfect for casual outings, festivals, or any occasion where you want to express your unique style.',
    subcategory: 'Jeans & Trousers',
    price: 45000, costPrice: 45000, stock: 1,
    tags: ['shorts', 'denim', 'blue', 'stones', 'alphabet', 'embellished', 'casual', 'womens'],
  },
  {
    sku: '219202211109',
    name: 'Home Straight Stoned Black Jean',
    description: 'A stunning pair of straight-cut black jeans with tasteful stone embellishments along the seams or pockets. The combination of classic denim and luxe stone detailing creates a jean that works equally well for casual and elevated looks.',
    subcategory: 'Jeans & Trousers',
    price: 75000, costPrice: 75000, stock: 1,
    tags: ['jeans', 'black', 'straight', 'stones', 'embellished', 'denim', 'womens'],
  },
  {
    sku: '219202011105',
    name: 'Sixth June Paris Black Jean Trouser',
    description: 'Sleek and contemporary black jean trousers by the cult Parisian brand Sixth June. Known for their clean, minimalist aesthetic and quality denim, these jeans deliver effortless Parisian cool in a versatile straight silhouette.',
    subcategory: 'Jeans & Trousers',
    price: 75000, costPrice: 75000, stock: 1,
    tags: ['jeans', 'black', 'sixth june', 'paris', 'designer', 'straight', 'womens'],
  },
  {
    sku: '219201811100',
    name: 'Cello Faded Black Jean',
    description: 'Washed and worn to perfection — the Cello faded black jean features a lived-in, artistically faded finish that adds depth and texture to classic black denim. A casual staple with serious style credentials.',
    subcategory: 'Jeans & Trousers',
    price: 75000, costPrice: 75000, stock: 1,
    tags: ['jeans', 'black', 'cello', 'faded', 'washed', 'denim', 'casual', 'womens'],
  },
  {
    sku: '219201711101',
    name: 'Noli Shop Stoned Leather Jean Trouser Size 38',
    description: 'A show-stopping pair of leather-finish jean trousers by Noli Shop in size 38, embellished with eye-catching stone detailing. The luxurious leather texture combined with sparkling stones creates a unique, high-fashion statement piece.',
    subcategory: 'Jeans & Trousers',
    price: 65000, costPrice: 65000, stock: 1,
    tags: ['jeans', 'leather', 'stoned', 'noli shop', 'embellished', 'size 38', 'fashion', 'womens'],
  },
  // ── SUITS & SETS ───────────────────────────────────────────────────────
  {
    sku: '219201391110',
    name: 'Blue Striped Double Button Jacket Size 38-46',
    description: 'A sharp and sophisticated blue striped double-button jacket, tailored for sizes 38 to 46. The bold stripe pattern and double-button closure give it a commanding presence, making it a perfect statement piece for formal or business occasions.',
    subcategory: 'Suits & Sets',
    price: 85000, costPrice: 85000, stock: 4,
    tags: ['jacket', 'blue', 'striped', 'double button', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219201401110',
    name: 'Pink Striped Double Button Jacket Size 38-46',
    description: 'A feminine and powerful pink striped double-button jacket for sizes 38 to 46. The soft pink tone with bold stripe detailing strikes the perfect balance between warmth and authority — ideal for power dressing with a feminine touch.',
    subcategory: 'Suits & Sets',
    price: 85000, costPrice: 85000, stock: 2,
    tags: ['jacket', 'pink', 'striped', 'double button', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219201381110',
    name: 'Carton Color Striped Double Button Jacket Size 38-46',
    description: 'A playful yet structured carton-color striped double-button jacket in sizes 38 to 46. The multi-stripe print adds a creative, artistic flair to this power jacket, making it a unique choice for the confident woman who loves to stand out.',
    subcategory: 'Suits & Sets',
    price: 85000, costPrice: 85000, stock: 5,
    tags: ['jacket', 'multicolor', 'striped', 'double button', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219201371110',
    name: 'Black Striped Double Button Jacket Size 38-46',
    description: 'A classic and authoritative black striped double-button jacket tailored for sizes 38 to 46. The sharp pinstripe on a black base delivers ultimate power-dressing credentials — perfect for boardrooms and formal settings.',
    subcategory: 'Suits & Sets',
    price: 85000, costPrice: 85000, stock: 5,
    tags: ['jacket', 'black', 'striped', 'double button', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219201021110',
    name: '2-Piece Black Jean & Pink Top Set',
    description: 'A coordinated 2-piece set pairing a chic black jean with a complementary pink top. This ready-to-wear matching set takes the guesswork out of styling, delivering a polished and effortlessly put-together look with minimal effort.',
    subcategory: 'Suits & Sets',
    price: 120000, costPrice: 120000, stock: 2,
    tags: ['set', '2-piece', 'black', 'pink', 'denim', 'casual', 'matching', 'womens'],
  },
  {
    sku: '219204411105',
    name: 'UZD Blue Double Breasted Skirt Suit Set Size 42/34',
    description: 'A refined and powerful blue double-breasted skirt suit set by UZD in size 42/34. The tailored blazer and coordinating skirt create an authoritative ensemble that speaks of confidence and professional elegance.',
    subcategory: 'Suits & Sets',
    price: 125000, costPrice: 125000, stock: 1,
    tags: ['suit', 'skirt suit', 'blue', 'uzd', 'double breasted', 'formal', 'womens'],
  },
  {
    sku: '219204311104',
    name: 'UZD Purple Double Breasted Skirt Suit Set Size 44-46',
    description: 'A regal and commanding purple double-breasted skirt suit set by UZD, available in sizes 44/36 and 46/38. Rich purple tones combined with sharp double-breasted tailoring create a powerful look for formal events and professional settings.',
    subcategory: 'Suits & Sets',
    price: 125000, costPrice: 125000, stock: 3,
    tags: ['suit', 'skirt suit', 'purple', 'uzd', 'double breasted', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219204511105',
    name: 'UZD Blue Double Breasted Skirt Suit Set Size 46/38',
    description: 'UZD blue double-breasted skirt suit in size 46/38 — a larger-size iteration of the classic tailored set. The sharp cut and bold double-breasted front deliver professional elegance in a flattering silhouette for the fuller figure.',
    subcategory: 'Suits & Sets',
    price: 125000, costPrice: 125000, stock: 1,
    tags: ['suit', 'skirt suit', 'blue', 'uzd', 'double breasted', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219201611109',
    name: 'Red With Black Inner 3-Piece Skirt Suit Size 50',
    description: 'A dramatic and luxurious 3-piece skirt suit in red with a black inner layer, sized 50. The bold contrast and multiple layers create a look of sophisticated grandeur — perfect for formal events and high-profile occasions where presence matters.',
    subcategory: 'Suits & Sets',
    price: 160000, costPrice: 160000, stock: 1,
    tags: ['suit', 'skirt suit', 'red', 'black', '3-piece', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219201511106',
    name: 'Black With Red Inner 3-Piece Skirt Suit Size 42-46',
    description: 'A bold and sophisticated 3-piece skirt suit in black with a striking red inner, available in sizes 42 to 46. The deep contrast between black and red creates a powerful visual impact, making this suit a statement piece for any formal occasion.',
    subcategory: 'Suits & Sets',
    price: 160000, costPrice: 160000, stock: 3,
    tags: ['suit', 'skirt suit', 'black', 'red', '3-piece', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219201411104',
    name: 'Red Double Breasted Pant Suit Size 42',
    description: 'A commanding and elegant red double-breasted pant suit in size 42. The rich red hue and sharp tailoring combine to create a power suit that makes an unforgettable impression in any formal or professional setting.',
    subcategory: 'Suits & Sets',
    price: 150000, costPrice: 150000, stock: 1,
    tags: ['suit', 'pant suit', 'red', 'double breasted', 'formal', 'tailored', 'womens'],
  },
  {
    sku: '219201211109',
    name: 'Green Double Breasted Pant Suit Size 44-46',
    description: 'A bold and sophisticated green double-breasted pant suit in sizes 44 and 46. The rich green tone and double-breasted cut create a look of commanding confidence — a perfect power dressing choice for the modern professional woman.',
    subcategory: 'Suits & Sets',
    price: 150000, costPrice: 150000, stock: 2,
    tags: ['suit', 'pant suit', 'green', 'double breasted', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219206111060',
    name: 'Blue With Rose & White Inner 3-Piece Skirt Suit Size 42',
    description: 'An elegant and romantic 3-piece skirt suit in blue with rose and white inner detailing, sized 42. The layered color scheme adds depth and femininity to this formal set, creating a look that is both authoritative and graceful.',
    subcategory: 'Suits & Sets',
    price: 160000, costPrice: 160000, stock: 1,
    tags: ['suit', 'skirt suit', 'blue', 'rose', 'white', '3-piece', 'formal', 'womens'],
  },
  {
    sku: '219207111008',
    name: 'Purple With Rose & White Inner 3-Piece Skirt Suit Size 44-48',
    description: 'A majestic 3-piece skirt suit in rich purple with rose and white inner layers, available in sizes 44 and 48. The regal purple hue and multi-layer construction create an extraordinary formal look for grand occasions and celebrations.',
    subcategory: 'Suits & Sets',
    price: 160000, costPrice: 160000, stock: 2,
    tags: ['suit', 'skirt suit', 'purple', 'rose', 'white', '3-piece', 'formal', 'plus size', 'womens'],
  },
  {
    sku: '219208111022',
    name: 'Green With Rose & White Inner 3-Piece Skirt Suit Size 42',
    description: 'A stunning 3-piece skirt suit in vibrant green with romantic rose and white inner accents, sized 42. This layered formal ensemble combines bold color with feminine detailing for a look of sophisticated celebration-worthy elegance.',
    subcategory: 'Suits & Sets',
    price: 160000, costPrice: 160000, stock: 1,
    tags: ['suit', 'skirt suit', 'green', 'rose', 'white', '3-piece', 'formal', 'womens'],
  },
  {
    sku: '219202511104',
    name: 'Animal Skin Skirt & Jacket Set',
    description: 'A fierce and coordinated animal skin-print skirt and jacket set. The matching print across both pieces creates a cohesive, editorial look full of wild confidence — perfect for women who love bold, unapologetic fashion.',
    subcategory: 'Suits & Sets',
    price: 95000, costPrice: 95000, stock: 1,
    tags: ['set', 'animal print', 'skirt', 'jacket', 'matching', 'bold', 'fashion', 'womens'],
  },
  {
    sku: '219202111033',
    name: 'Marco Donateli Sky Blue 2-Piece Shorts & Top Set Size M',
    description: 'A stylish and well-coordinated sky blue 2-piece shorts and top set by Marco Donateli in size M. The matching sky blue coordinates create an effortlessly put-together look that is fresh, casual, and perfect for warm-weather styling.',
    subcategory: 'Suits & Sets',
    price: 65000, costPrice: 65000, stock: 1,
    tags: ['set', '2-piece', 'sky blue', 'marco donateli', 'shorts', 'top', 'size m', 'casual', 'womens'],
  },
  // ── LINGERIE & LOUNGEWEAR ──────────────────────────────────────────────
  {
    sku: '219201091110',
    name: 'Body Suit & Sleeveless Sky Blue M-3XL',
    description: 'A sleek and comfortable sky blue bodysuit with a sleeveless design, available from M to 3XL. Its stretchy, form-fitting construction provides a seamless, polished base layer that pairs beautifully with any bottom for a refined, put-together look.',
    subcategory: 'Lingerie & Loungewear',
    price: 35000, costPrice: 35000, stock: 5,
    tags: ['bodysuit', 'sky blue', 'sleeveless', 'comfortable', 'plus size', 'womens'],
  },
  {
    sku: '219201081110',
    name: 'Body Suit & Sleeveless Royal Blue M-3XL',
    description: 'A rich royal blue bodysuit with a clean sleeveless design in sizes M to 3XL. Its form-fitting, stretchy fabric creates a seamless silhouette — the ideal foundational piece to wear tucked into skirts, trousers, or high-waisted bottoms.',
    subcategory: 'Lingerie & Loungewear',
    price: 35000, costPrice: 35000, stock: 5,
    tags: ['bodysuit', 'royal blue', 'sleeveless', 'comfortable', 'plus size', 'womens'],
  },
  {
    sku: '219201071110',
    name: 'Body Suit & Sleeveless Black M-3XL',
    description: 'A classic black sleeveless bodysuit in sizes M to 3XL — the ultimate wardrobe staple. Its second-skin fit and clean silhouette make it the perfect layering piece under blazers, cardigans, or worn alone with tailored trousers.',
    subcategory: 'Lingerie & Loungewear',
    price: 35000, costPrice: 35000, stock: 5,
    tags: ['bodysuit', 'black', 'sleeveless', 'comfortable', 'plus size', 'essential', 'womens'],
  },
  {
    sku: '219201061110',
    name: 'Body Suit & Sleeveless Brown M-3XL',
    description: 'A warm and earthy brown sleeveless bodysuit available from M to 3XL. Its smooth, form-fitting construction provides a seamless base for any outfit, while the rich brown tone complements a wide range of complexions beautifully.',
    subcategory: 'Lingerie & Loungewear',
    price: 35000, costPrice: 35000, stock: 5,
    tags: ['bodysuit', 'brown', 'sleeveless', 'comfortable', 'plus size', 'womens'],
  },
  {
    sku: '219201051110',
    name: 'Body Suit & Sleeveless Yellow M-3XL',
    description: 'A vibrant and mood-lifting yellow sleeveless bodysuit in sizes M to 3XL. Its cheerful color and snug, stretchy fit make it a standout base layer or standalone top that brings instant sunshine to any outfit.',
    subcategory: 'Lingerie & Loungewear',
    price: 35000, costPrice: 35000, stock: 5,
    tags: ['bodysuit', 'yellow', 'sleeveless', 'comfortable', 'plus size', 'bright', 'womens'],
  },
  {
    sku: '219208611100',
    name: 'Coccolarsi Pajama Set Pink',
    description: 'Wrap yourself in luxury with the Coccolarsi pajama set in a soft, feminine pink. Known for their buttery-smooth fabric and relaxed fit, Coccolarsi PJ sets are the gold standard of premium loungewear — cozy, chic, and indulgent.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 3,
    tags: ['pajamas', 'coccolarsi', 'pink', 'loungewear', 'luxury', 'comfortable', 'womens'],
  },
  {
    sku: '219209211108',
    name: 'Coccolarsi Pajama Set Red',
    description: 'The Coccolarsi luxury pajama set in bold red — a vibrant take on premium loungewear. Crafted from ultra-soft fabric for an enveloping, comfortable feel, this PJ set is as much a treat for yourself as it is a thoughtful gift.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 3,
    tags: ['pajamas', 'coccolarsi', 'red', 'loungewear', 'luxury', 'comfortable', 'womens'],
  },
  {
    sku: '219209711104',
    name: 'Louis Vuitton Pajama Set Black',
    description: 'Indulge in the ultimate luxury loungewear with this Louis Vuitton-inspired pajama set in sophisticated black. Featuring premium fabric, relaxed tailoring, and the iconic LV aesthetic, this PJ set transforms bedtime into a luxury experience.',
    subcategory: 'Lingerie & Loungewear',
    price: 85000, costPrice: 85000, stock: 4,
    tags: ['pajamas', 'louis vuitton', 'black', 'loungewear', 'luxury', 'designer', 'womens'],
  },
  {
    sku: '219209611109',
    name: 'Coccolarsi Pajama Set Off White',
    description: 'Effortlessly elegant in off-white, the Coccolarsi pajama set delivers understated luxury. The soft, neutral tone and premium fabric make this the ideal set for restful nights and lazy morning lounging in sophisticated comfort.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 4,
    tags: ['pajamas', 'coccolarsi', 'off white', 'loungewear', 'luxury', 'comfortable', 'womens'],
  },
  {
    sku: '219209511103',
    name: 'Coccolarsi Pajama Set Black',
    description: 'Sleek and luxurious in classic black, the Coccolarsi pajama set is a must-have in every woman\'s loungewear wardrobe. Premium soft fabric and relaxed, flattering silhouette make every evening feel like a self-care ritual.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 4,
    tags: ['pajamas', 'coccolarsi', 'black', 'loungewear', 'luxury', 'comfortable', 'womens'],
  },
  {
    sku: '219209411102',
    name: 'Coccolarsi Pajama Set Ash',
    description: 'Cool and contemporary in ash grey, the Coccolarsi pajama set offers modern-toned luxury loungewear. The soft grey hue and premium buttery fabric make this set as stylish as it is comfortable — perfect for home and holiday.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 4,
    tags: ['pajamas', 'coccolarsi', 'ash', 'grey', 'loungewear', 'luxury', 'comfortable', 'womens'],
  },
  {
    sku: '219209311103',
    name: 'Coccolarsi Pajama Set Green',
    description: 'The Coccolarsi pajama set in a fresh, calming green — a natural and serene choice for luxury loungewear. Crafted from their signature soft fabric, this PJ set wraps you in comfort and style for the perfect restful evening.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 4,
    tags: ['pajamas', 'coccolarsi', 'green', 'loungewear', 'luxury', 'comfortable', 'womens'],
  },
  {
    sku: '219209111101',
    name: 'Dior Black & White Pajama Set',
    description: 'Luxurious Dior-inspired pajama set in a crisp black and white colorway. The iconic contrast and premium fabric construction deliver the feeling of high-fashion comfort — an exquisite loungewear set that blends elegance with indulgence.',
    subcategory: 'Lingerie & Loungewear',
    price: 90000, costPrice: 90000, stock: 4,
    tags: ['pajamas', 'dior', 'black', 'white', 'loungewear', 'luxury', 'designer', 'womens'],
  },
  {
    sku: '219209011103',
    name: 'Dior Coffee Brown Pajama Set',
    description: 'A warm and indulgent Dior-inspired pajama set in rich coffee brown. The deep, sophisticated hue and premium soft fabric create a luxurious loungewear experience that is both calming and effortlessly stylish.',
    subcategory: 'Lingerie & Loungewear',
    price: 90000, costPrice: 90000, stock: 4,
    tags: ['pajamas', 'dior', 'coffee brown', 'loungewear', 'luxury', 'designer', 'womens'],
  },
  {
    sku: '219208911105',
    name: 'Victoria\'s Secret Pink & Black Lingerie Set',
    description: 'A seductive and playful pink and black lingerie set by Victoria\'s Secret. Featuring feminine lace detailing and a flattering cut, this set brings the iconic VS combination of comfort and allure together in a beautifully crafted piece.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 4,
    tags: ["victoria's secret", 'vs', 'pink', 'black', 'lingerie', 'lace', 'sensual', 'womens'],
  },
  {
    sku: '219208811104',
    name: 'Coccolarsi Pajama Set Turquoise Blue',
    description: 'Vibrant and refreshing, the Coccolarsi pajama set in turquoise blue brings a tropical energy to luxury loungewear. The striking color and signature soft fabric make this set a beautiful and practical wardrobe addition.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 4,
    tags: ['pajamas', 'coccolarsi', 'turquoise', 'blue', 'loungewear', 'luxury', 'comfortable', 'womens'],
  },
  {
    sku: '219208711102',
    name: 'Coccolarsi Pajama Set Black & Grey',
    description: 'A sophisticated black and grey Coccolarsi pajama set that brings a modern, minimalist aesthetic to premium loungewear. The two-tone design and buttery-soft fabric create a versatile and stylish set for relaxed evenings and restful nights.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 4,
    tags: ['pajamas', 'coccolarsi', 'black', 'grey', 'loungewear', 'luxury', 'comfortable', 'womens'],
  },
  {
    sku: '219208311106',
    name: 'Victoria\'s Secret Black & Red Lingerie Set',
    description: 'A bold and sultry black and red lingerie set by Victoria\'s Secret. The dramatic color contrast and intricate lace details create a set that is passionate, feminine, and designed to make you feel irresistibly confident.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 3,
    tags: ["victoria's secret", 'vs', 'black', 'red', 'lingerie', 'lace', 'sensual', 'womens'],
  },
  {
    sku: '219208211103',
    name: 'Victoria\'s Secret Coffee Brown Lingerie Set',
    description: 'A rich and sensual coffee brown lingerie set by Victoria\'s Secret. The warm, earthy tone and delicate construction create a set that is quietly luxurious and effortlessly feminine, perfect for the woman who appreciates understated allure.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 2,
    tags: ["victoria's secret", 'vs', 'coffee brown', 'lingerie', 'sensual', 'womens'],
  },
  {
    sku: '219208111107',
    name: 'Victoria\'s Secret Ox Blood Plain Lingerie Set',
    description: 'A deep, moody ox blood red lingerie set by Victoria\'s Secret with a clean, minimalist construction. The rich, dark burgundy tone adds an air of mystery and sophistication to this beautifully crafted set.',
    subcategory: 'Lingerie & Loungewear',
    price: 75000, costPrice: 75000, stock: 1,
    tags: ["victoria's secret", 'vs', 'ox blood', 'burgundy', 'lingerie', 'sensual', 'womens'],
  },
  {
    sku: '219209811104',
    name: '2-Piece Teddy Bear Pant Set',
    description: 'An adorably cozy and playful 2-piece teddy bear print pant set that brings warmth and fun to loungewear. Soft, comfortable, and irresistibly cute — this set is perfect for relaxed days at home and cozy nights in.',
    subcategory: 'Lingerie & Loungewear',
    price: 85000, costPrice: 85000, stock: 4,
    tags: ['pajamas', 'teddy bear', 'print', '2-piece', 'cozy', 'loungewear', 'womens'],
  },
  {
    sku: '219208011105',
    name: 'Fazve Sexy Lingerie',
    description: 'A sultry and alluring lingerie piece by Fazve, crafted to celebrate femininity and confidence. Its delicate construction, flattering cut, and seductive design make it a beautiful addition to any intimate wardrobe.',
    subcategory: 'Lingerie & Loungewear',
    price: 45000, costPrice: 45000, stock: 1,
    tags: ['lingerie', 'fazve', 'sensual', 'feminine', 'intimate', 'womens'],
  },
  {
    sku: '219207911101',
    name: 'Jia Yan Sexy Underwear',
    description: 'Beautiful and feminine underwear by Jia Yan, crafted with attention to detail and comfort. Its flattering cut and delicate design make it a luxurious and intimate wardrobe essential for the confident woman.',
    subcategory: 'Lingerie & Loungewear',
    price: 45000, costPrice: 45000, stock: 1,
    tags: ['underwear', 'jia yan', 'lingerie', 'feminine', 'intimate', 'womens'],
  },
  // ── TRADITIONAL & ETHNIC ───────────────────────────────────────────────
  {
    sku: '219202911108',
    name: 'Onion & Navy Blue Katalia Flair 2-Colored Abaya',
    description: 'An elegant and flowing two-colored Abaya by Katalia in beautiful onion pink and navy blue. The two-tone flair design creates a graceful, layered silhouette that moves beautifully — combining modesty with contemporary fashion sensibility.',
    subcategory: 'Traditional & Ethnic',
    price: 125000, costPrice: 125000, stock: 1,
    tags: ['abaya', 'katalia', 'onion pink', 'navy blue', 'modest fashion', 'traditional', 'flair', 'womens'],
  },
  // ── ACCESSORIES ────────────────────────────────────────────────────────
  {
    sku: '219206011109',
    name: 'Adult Designer Panty Hose',
    description: 'Luxuriously crafted designer panty hose for the fashion-conscious woman. Smooth, durable, and elegantly sheer, these hosiery essentials provide a polished, put-together finish to any formal or smart-casual outfit.',
    subcategory: 'Accessories',
    price: 40000, costPrice: 40000, stock: 16,
    tags: ['hosiery', 'panty hose', 'designer', 'accessories', 'formal', 'womens'],
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');

  let inserted = 0;
  let skipped = 0;

  for (const p of products) {
    const slug = slugify(p.name);
    const exists = await Product.findOne({ $or: [{ barcode: p.sku }, { slug }] });
    if (exists) {
      console.log(`  SKIP: ${p.name}`);
      skipped++;
      continue;
    }
    await Product.create({
      name: p.name,
      slug,
      description: p.description,
      category: 'Female Fashion',
      subcategory: p.subcategory,
      barcode: p.sku,
      tags: p.tags,
      status: 'published',
      variants: [{ sku: p.sku, price: p.price, costPrice: p.costPrice, stock: p.stock }],
    });
    console.log(`  OK: ${p.name}`);
    inserted++;
  }

  console.log(`\nDone. Inserted: ${inserted}, Skipped: ${skipped}`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
