require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Product = require('../models/Product');

const slugify = (name) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const products = [
  {
    sku: '000741',
    name: 'CD Dior Sauvage Parfum',
    description: 'A bold and magnetic fragrance from Christian Dior, Sauvage Parfum opens with a fresh burst of bergamot before revealing its intense woody heart. This parfum concentration intensifies the iconic Sauvage DNA — raw, noble, and deeply masculine. A modern classic for the confident man.',
    category: 'Perfumes',
    subcategory: "Men's Fragrances",
    price: 455000,
    costPrice: 455000,
    stock: 1,
    barcode: '000741',
    tags: ['dior', 'sauvage', 'parfum', 'mens', 'woody', 'fresh', 'bergamot', 'luxury', 'designer'],
  },
  {
    sku: '219218111005',
    name: 'Amouage Opus VII',
    description: 'Amouage Opus VII is a masterpiece of olfactory art from the Omani luxury house. This rich and complex fragrance weaves together smoky incense, dark resins, and velvety woods into an opulent tapestry. A contemplative, mysterious scent for those who appreciate the finest in niche perfumery.',
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 750000,
    costPrice: 750000,
    stock: 1,
    barcode: '219218111005',
    tags: ['amouage', 'opus', 'niche', 'luxury', 'oud', 'incense', 'woody', 'smoky', 'unisex'],
  },
  {
    sku: '219221111044',
    name: 'Amouage Rose Incense',
    description: 'A breathtaking union of velvety rose and sacred incense from Amouage. Rose Incense captures the soul of the Middle East through an opulent floral heart enveloped in smoky frankincense and warm woods. Timeless and spiritual, this is a fragrance for moments of deep contemplation and elegance.',
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 720000,
    costPrice: 720000,
    stock: 1,
    barcode: '219221111044',
    tags: ['amouage', 'rose', 'incense', 'floral', 'luxury', 'niche', 'oriental', 'unisex', 'frankincense'],
  },
  {
    sku: '219244111087',
    name: 'Idole Lancôme',
    description: 'Idole by Lancôme is a radiant, modern floral fragrance that celebrates feminine strength and independence. A luminous rose heart mingles with musk and cedarwood to create a scent that is both delicate and powerful. Beautifully crafted for the bold, idealistic woman of today.',
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 230000,
    costPrice: 230000,
    stock: 1,
    barcode: '219244111087',
    tags: ['lancome', 'idole', 'womens', 'floral', 'rose', 'modern', 'feminine', 'designer'],
  },
  {
    sku: '219243111033',
    name: "Very Sexy Oasis Victoria's Secret",
    description: "Victoria's Secret Very Sexy Oasis is a light and sensual fruity-floral fragrance. Crisp cucumber water and melon blend with white florals and a hint of musk to create a refreshing yet alluring scent — perfect for the warm-weather woman who loves a playful, flirtatious touch.",
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 95000,
    costPrice: 95000,
    stock: 1,
    barcode: '219243111033',
    tags: ["victoria's secret", 'very sexy', 'oasis', 'fruity', 'floral', 'womens', 'fresh', 'playful'],
  },
  {
    sku: '219242111030',
    name: 'Club de Nuit Armaf',
    description: 'Club de Nuit by Armaf is a luxurious and sophisticated fragrance inspired by the legendary Creed Aventus. Opening with fresh pineapple and citrus, it transitions into a heart of birch, rose, and jasmine before settling on a rich base of musk, ambergris, and oakmoss. Boldly elegant.',
    category: 'Perfumes',
    subcategory: "Men's Fragrances",
    price: 85000,
    costPrice: 85000,
    stock: 1,
    barcode: '219242111030',
    tags: ['armaf', 'club de nuit', 'mens', 'fresh', 'fruity', 'woody', 'masculine', 'inspired by creed'],
  },
  {
    sku: '219271110914',
    name: 'Scandal Women Jean Paul Gaultier',
    description: "Jean Paul Gaultier Scandal is a provocative and addictive floral fragrance that breaks all the rules. A honeyed gardenia heart is anchored by caramel and patchouli in a seductive blend that is both sweet and daring. Housed in the iconic golden legs bottle, it's a statement scent for the bold woman.",
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 230000,
    costPrice: 230000,
    stock: 3,
    barcode: '219271110914',
    tags: ['jean paul gaultier', 'scandal', 'womens', 'floral', 'honey', 'patchouli', 'sensual', 'designer'],
  },
  {
    sku: '219261110436',
    name: 'Scandal Men Jean Paul Gaultier',
    description: "Jean Paul Gaultier Scandal Pour Homme is a daring and sophisticated aromatic fougère. Fresh mandarin and blood orange open the fragrance, while a heart of sage and lavender delivers a clean masculinity. The base of tonka bean and vetiver gives it a warm, addictive trail. Refined yet provocative.",
    category: 'Perfumes',
    subcategory: "Men's Fragrances",
    price: 195000,
    costPrice: 195000,
    stock: 1,
    barcode: '219261110436',
    tags: ['jean paul gaultier', 'scandal', 'mens', 'aromatic', 'citrus', 'fougere', 'tonka', 'designer'],
  },
  {
    sku: '219219111093',
    name: 'Amouage Interlude Man',
    description: 'Amouage Interlude Man is an iconic fragrance capturing a moment of transition and drama. Oregano, bergamot, and amber open the journey, evolving through a complex heart of orris and labdanum into a deep, smoky base of oud and sandalwood. A bold, unforgettable statement in niche perfumery.',
    category: 'Perfumes',
    subcategory: "Men's Fragrances",
    price: 650000,
    costPrice: 650000,
    stock: 3,
    barcode: '219219111093',
    tags: ['amouage', 'interlude', 'mens', 'oud', 'woody', 'smoky', 'luxury', 'niche', 'amber'],
  },
  {
    sku: '219216111090',
    name: 'Amouage Opus V',
    description: 'Amouage Opus V is a dark, resinous, and deeply sensual fragrance from the celebrated Library Collection. With notes of cumin, coriander, rose, and labdanum intertwined with smoky woods, it evokes ancient spice routes and mysterious rituals. An extraordinary experience for the connoisseur.',
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 680000,
    costPrice: 680000,
    stock: 1,
    barcode: '219216111090',
    tags: ['amouage', 'opus', 'library collection', 'niche', 'luxury', 'spicy', 'woody', 'oriental', 'unisex'],
  },
  {
    sku: '219229111024',
    name: 'Amouage Reckless Leather',
    description: 'Amouage Reckless Leather is a bold and commanding leather fragrance with a rebellious spirit. Smoky birch tar and rich leather are softened by floral accords and warm amber, creating a scent that is unapologetically daring yet undeniably sophisticated. For those who live life on their own terms.',
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 520000,
    costPrice: 520000,
    stock: 1,
    barcode: '219229111024',
    tags: ['amouage', 'leather', 'reckless', 'niche', 'luxury', 'smoky', 'bold', 'unisex', 'woody'],
  },
  {
    sku: '219239111083',
    name: 'Burberry Touch Woman',
    description: "Burberry Touch for Women is a soft, sensual floral fragrance that evokes the feeling of skin on skin. A gentle blend of white cedar, peony, and vanilla creates a warm, intimate, and effortlessly feminine scent. It's the essence of quiet luxury — understated, British, and beautifully tactile.",
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 110000,
    costPrice: 110000,
    stock: 1,
    barcode: '219239111083',
    tags: ['burberry', 'touch', 'womens', 'floral', 'vanilla', 'soft', 'feminine', 'designer'],
  },
  {
    sku: '219210111033',
    name: 'Burberry Her',
    description: "Burberry Her is a vibrant fruity-floral fragrance celebrating the free-spirited energy of London. Juicy notes of blackcurrant, blackberry, and raspberry are wrapped in a white floral heart with a soft musk base. Fresh, youthful, and full of life — it's London in a bottle.",
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 180000,
    costPrice: 180000,
    stock: 1,
    barcode: '219210111033',
    tags: ['burberry', 'her', 'womens', 'fruity', 'floral', 'fresh', 'berry', 'designer', 'youthful'],
  },
  {
    sku: '219236111097',
    name: 'Versace Crystal Noir',
    description: "Versace Crystal Noir is an enigmatic and seductive fragrance shrouded in mystery. A dark floral heart of gardenia, peony, and coconut blooms over a base of sandalwood and musk, creating an intensely feminine and hypnotic scent. The embodiment of Versace's glamorous and mysterious allure.",
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 210000,
    costPrice: 210000,
    stock: 1,
    barcode: '219236111097',
    tags: ['versace', 'crystal noir', 'womens', 'floral', 'oriental', 'sandalwood', 'sensual', 'designer'],
  },
  {
    sku: '219237111022',
    name: 'Paco Rabanne Absolutely Gold',
    description: 'Paco Rabanne Absolutely Gold is a sumptuous and opulent feminine fragrance that glitters with luxury. A golden floral composition of rose, jasmine, and ylang-ylang sits on a rich base of patchouli and amber, creating a powerful, radiant, and unapologetically glamorous scent.',
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 230000,
    costPrice: 230000,
    stock: 1,
    barcode: '219237111022',
    tags: ['paco rabanne', 'absolutely gold', 'womens', 'floral', 'rose', 'jasmine', 'opulent', 'designer', 'luxury'],
  },
  {
    sku: '219241111092',
    name: 'Franck Olivier Oud Vanille',
    description: 'Franck Olivier Oud Vanille is an indulgent oriental fragrance that fuses the deep, smoky richness of oud with the warm sweetness of vanilla. Amber and sandalwood round out the base, creating a luxuriously cozy and sensual fragrance that lingers beautifully on the skin.',
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 55000,
    costPrice: 55000,
    stock: 1,
    barcode: '219241111092',
    tags: ['franck olivier', 'oud', 'vanilla', 'oriental', 'sweet', 'woody', 'amber', 'unisex'],
  },
  {
    sku: '219215111098',
    name: 'Amouage Opus X',
    description: "Amouage Opus X is the most avant-garde entry in the Library Collection — a striking, almost abstract fragrance that begins with sharp aldehydes and beeswax before melting into a floral heart and a base of vetiver and oud. Challenging, beautiful, and utterly distinctive. Not for the timid.",
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 750000,
    costPrice: 750000,
    stock: 1,
    barcode: '219215111098',
    tags: ['amouage', 'opus', 'library collection', 'niche', 'luxury', 'abstract', 'oud', 'vetiver', 'unisex'],
  },
  {
    sku: '219217111028',
    name: 'Amouage Opus VI',
    description: "Amouage Opus VI is a haunting and ethereal fragrance inspired by the concept of loss and longing. A translucent iris and violet leaf open over a soft, powdery base of ambergris and musk. Melancholic yet beautiful, it is a scent of rare emotional depth from one of the world's finest houses.",
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 680000,
    costPrice: 680000,
    stock: 1,
    barcode: '219217111028',
    tags: ['amouage', 'opus', 'library collection', 'niche', 'luxury', 'iris', 'powdery', 'floral', 'unisex'],
  },
  {
    sku: '219240111063',
    name: 'Giorgio Armani My Way Intense',
    description: "Giorgio Armani My Way Intense is a deeper, more sensual interpretation of the beloved My Way. A heart of tuberose and orange blossom is enriched with Bourbon vanilla and white musk for a warmer, more enveloping embrace. It's a fragrance about openness — to the world and to human connection.",
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 230000,
    costPrice: 230000,
    stock: 1,
    barcode: '219240111063',
    tags: ['giorgio armani', 'my way', 'intense', 'womens', 'floral', 'vanilla', 'tuberose', 'designer'],
  },
  {
    sku: '219234111090',
    name: 'Jimmy Choo I Want Choo',
    description: 'Jimmy Choo I Want Choo is a playful, sparkling fragrance for the modern femme fatale. The scent opens with exotic pitanga and daffodil, evolving into a heart of tiger lily and jasmine. A velvety base of creamy sandalwood and musk seals in its irresistible warmth and femininity.',
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 185000,
    costPrice: 185000,
    stock: 2,
    barcode: '219234111090',
    tags: ['jimmy choo', 'i want choo', 'womens', 'floral', 'fruity', 'jasmine', 'sandalwood', 'designer'],
  },
  {
    sku: '219235111077',
    name: 'Jimmy Choo I Want Choo Forever',
    description: "Jimmy Choo I Want Choo Forever is the eternally romantic follow-up, built for the woman who dares to dream big. A luminous blend of passionfruit and freesia blooms into a heart of orange blossom and heliotrope, resting on a warm base of musk and sandalwood — it's love captured in a bottle.",
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 195000,
    costPrice: 195000,
    stock: 2,
    barcode: '219235111077',
    tags: ['jimmy choo', 'i want choo forever', 'womens', 'floral', 'romantic', 'passionfruit', 'sandalwood', 'designer'],
  },
  {
    sku: '219225111005',
    name: 'Acqua di Parma Oud',
    description: "Acqua di Parma Oud is a majestic and sophisticated oriental fragrance from one of Italy's most prestigious houses. Precious oud is layered with rose, saffron, patchouli, and leather to create a rich, luxurious composition that speaks to the Italian tradition of craftsmanship fused with Eastern opulence.",
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 290000,
    costPrice: 290000,
    stock: 1,
    barcode: '219225111005',
    tags: ['acqua di parma', 'oud', 'luxury', 'oriental', 'italian', 'rose', 'saffron', 'niche', 'unisex'],
  },
  {
    sku: '219233111040',
    name: 'SF Spicy Leather',
    description: 'SF Spicy Leather is an assertive and charismatic fragrance that fuses the warmth of spices with the boldness of leather. Cardamom and black pepper open with a fiery intensity, softened by a heart of rose and labdanum, before a deep leather and oud base anchors the composition with commanding presence.',
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 150000,
    costPrice: 150000,
    stock: 1,
    barcode: '219233111040',
    tags: ['sf', 'spicy', 'leather', 'oriental', 'oud', 'cardamom', 'unisex', 'bold', 'pepper'],
  },
  {
    sku: '219232111034',
    name: 'SF Intense Leather',
    description: 'SF Intense Leather is a raw and unapologetic leather fragrance that makes a powerful first impression. Notes of birch tar, smoky oud, and dark resins build an intense leather core, while subtle florals and cedarwood add depth and sophistication. For those who command attention without saying a word.',
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 150000,
    costPrice: 150000,
    stock: 1,
    barcode: '219232111034',
    tags: ['sf', 'intense', 'leather', 'oud', 'smoky', 'dark', 'oriental', 'unisex', 'bold'],
  },
  {
    sku: '219220111056',
    name: 'Amouage Jubilation XXV',
    description: "Amouage Jubilation XXV is a grand, celebratory fragrance created for the house's 25th anniversary. An extraordinary blend of labdanum, myrrh, frankincense, and precious woods unfolds over time in a rich, ceremonial composition. One of the great masterpieces of contemporary perfumery.",
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 750000,
    costPrice: 750000,
    stock: 1,
    barcode: '219220111056',
    tags: ['amouage', 'jubilation', 'anniversary', 'luxury', 'niche', 'incense', 'oud', 'frankincense', 'unisex'],
  },
  {
    sku: '219227111015',
    name: 'Memo Paris Italian Leather',
    description: "Memo Paris Italian Leather is a love letter to the artisans of Florence. Inspired by the scent of fine Italian leather ateliers, it combines soft iris, cedarwood, and clean musk with supple leather accords. Refined, elegant, and deeply nostalgic — a fragrance that tells a story of craft and beauty.",
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 310000,
    costPrice: 310000,
    stock: 1,
    barcode: '219227111015',
    tags: ['memo paris', 'italian leather', 'leather', 'iris', 'niche', 'luxury', 'unisex', 'woody', 'florence'],
  },
  {
    sku: '219226111025',
    name: 'Memo Paris Irish Leather',
    description: 'Memo Paris Irish Leather evokes the wild, windswept landscapes of the Emerald Isle. Fresh green notes and sea breeze mingle with smooth leather, heather, and earthy moss in a fragrance that feels both untamed and elegant. A journey through the rugged beauty of Ireland in every spray.',
    category: 'Perfumes',
    subcategory: 'Niche & Luxury',
    price: 390000,
    costPrice: 390000,
    stock: 1,
    barcode: '219226111025',
    tags: ['memo paris', 'irish leather', 'leather', 'green', 'niche', 'luxury', 'unisex', 'fresh', 'mossy'],
  },
  {
    sku: '219224111051',
    name: 'Creed Green Irish Tweed',
    description: "Creed Green Irish Tweed is one of the world's most celebrated and enduring masculine fragrances. An iconic blend of French iris, verbena, and sandalwood creates a fresh, crisp, yet deeply sophisticated scent. Said to be the inspiration for countless imitators, the original remains timeless and unmatched.",
    category: 'Perfumes',
    subcategory: "Men's Fragrances",
    price: 590000,
    costPrice: 590000,
    stock: 1,
    barcode: '219224111051',
    tags: ['creed', 'green irish tweed', 'mens', 'fresh', 'iris', 'sandalwood', 'luxury', 'niche', 'classic', 'iconic'],
  },
  {
    sku: '219211111095',
    name: 'Good Girl Carolina Herrera',
    description: "Carolina Herrera Good Girl is a seductive duality — the conflict between good and evil, day and night. A bright floral of jasmine sambac and tuberose contrasts with a dark, addictive base of tonka bean, cocoa, and vetiver. Housed in the iconic high-heel bottle, it's the ultimate statement fragrance.",
    category: 'Perfumes',
    subcategory: "Women's Fragrances",
    price: 200000,
    costPrice: 200000,
    stock: 1,
    barcode: '219211111095',
    tags: ['carolina herrera', 'good girl', 'womens', 'floral', 'jasmine', 'tonka', 'sensual', 'designer', 'iconic'],
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');

  let inserted = 0;
  let skipped = 0;

  for (const p of products) {
    const slug = slugify(p.name);
    const exists = await Product.findOne({ $or: [{ barcode: p.sku }, { slug }] });
    if (exists) {
      console.log(`  SKIP: ${p.name} (already exists)`);
      skipped++;
      continue;
    }

    await Product.create({
      name: p.name,
      slug,
      description: p.description,
      category: p.category,
      subcategory: p.subcategory,
      barcode: p.sku,
      tags: p.tags,
      status: 'published',
      variants: [
        {
          sku: p.sku,
          price: p.price,
          costPrice: p.costPrice,
          stock: p.stock,
        },
      ],
    });
    console.log(`  OK: ${p.name}`);
    inserted++;
  }

  console.log(`\nDone. Inserted: ${inserted}, Skipped: ${skipped}`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
