require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");
const Product = require("../models/Product");

const slugify = (name) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const products = [
  // ───────────────────── SHIRTS ─────────────────────
  {
    sku: "219438311108",
    name: "White & Grey Amiri Short Sleeve Shirt",
    description: "A premium short-sleeve shirt from Amiri featuring a classic white and grey colorway. Crafted with meticulous attention to detail, this shirt delivers the brand's signature rock-luxe aesthetic with a relaxed, effortlessly cool silhouette perfect for smart-casual occasions.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 110000,
    costPrice: 110000,
    stock: 4,
    barcode: "219438311108",
    tags: ["amiri", "shirt", "white", "grey", "short sleeve", "designer", "mens", "luxury"],
  },
  {
    sku: "219316111100",
    name: "Denim Tears Short Sleeve Shirt",
    description: "A statement short-sleeve shirt from Denim Tears, the culturally driven streetwear label. Features the brand's distinctive graphic identity and premium cotton construction. A must-have for collectors and streetwear enthusiasts who appreciate fashion with a deeper narrative.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 110000,
    costPrice: 110000,
    stock: 4,
    barcode: "219316111100",
    tags: ["denim tears", "shirt", "short sleeve", "streetwear", "designer", "mens", "graphic"],
  },
  {
    sku: "219316311106",
    name: "Animal Skin Color Versace Corp Shirt",
    description: "A bold corporate shirt from Versace featuring an eye-catching animal skin print. The iconic Versace craftsmanship meets a daring pattern for a shirt that commands attention. Ideal for the man who wants to make a statement at formal and semi-formal events.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 75000,
    costPrice: 75000,
    stock: 6,
    barcode: "219316311106",
    tags: ["versace", "shirt", "animal print", "corporate", "designer", "mens", "bold"],
  },
  {
    sku: "219316211107",
    name: "White & Black Dolce & Gabbana Corp Shirt",
    description: "A sharp two-tone corporate shirt from Dolce & Gabbana in a striking white and black combination. Features the brand's impeccable Italian tailoring and refined finishing. Elevates any formal wardrobe with its clean contrast and luxurious feel.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 3,
    barcode: "219316211107",
    tags: ["dolce gabbana", "d&g", "shirt", "white", "black", "corporate", "designer", "mens", "italian"],
  },
  {
    sku: "219191051110",
    name: "Blue Jean MR110-1",
    description: "A classic straight-cut blue wash denim jean from the MR110-1 collection. Available in waist sizes 31, 36, and 38. Features a clean, versatile silhouette with a comfortable mid-rise waist and durable fabric — a wardrobe staple for any well-dressed man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 6,
    barcode: "219191051110",
    tags: ["jeans", "blue", "denim", "MR110", "straight fit", "mens", "casual"],
  },
  {
    sku: "219191221110",
    name: "White Versace Couture Corp Shirt",
    description: "A crisp all-white corporate shirt bearing the prestigious Versace Couture label. Tailored for elegance and refinement, it features premium fabric and precise detailing that showcase the brand's Italian heritage. The perfect foundation for a polished formal look.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 3,
    barcode: "219191221110",
    tags: ["versace", "couture", "shirt", "white", "corporate", "designer", "mens", "formal"],
  },
  {
    sku: "219191211110",
    name: "Multicolored Dolce & Gabbana Corp Shirt",
    description: "An expressive multicolored corporate shirt from Dolce & Gabbana. The vibrant print reflects the brand's love of bold Italian artistry and joie de vivre. A conversation-starting piece that brings personality and flair to any smart wardrobe.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 5,
    barcode: "219191211110",
    tags: ["dolce gabbana", "d&g", "shirt", "multicolored", "corporate", "designer", "mens", "italian"],
  },
  {
    sku: "219191201110",
    name: "Coffee Brown Dolce & Gabbana Corp Shirt",
    description: "A sophisticated coffee-brown corporate shirt from Dolce & Gabbana. The warm earthy tone is elevated by the brand's expert tailoring and luxurious fabric. An understated yet distinctly high-end choice for the style-conscious professional.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 75000,
    costPrice: 75000,
    stock: 5,
    barcode: "219191201110",
    tags: ["dolce gabbana", "d&g", "shirt", "brown", "coffee", "corporate", "designer", "mens"],
  },
  {
    sku: "219191191110",
    name: "Tiger Face Dolce & Gabbana Corp Shirt",
    description: "A dramatic and luxurious corporate shirt from Dolce & Gabbana featuring a striking tiger face motif. This bold piece channels the brand's love of theatrical Italian glamour. For the confident man who wants his wardrobe to leave a lasting impression.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 75000,
    costPrice: 75000,
    stock: 6,
    barcode: "219191191110",
    tags: ["dolce gabbana", "d&g", "shirt", "tiger", "animal print", "corporate", "designer", "mens"],
  },
  {
    sku: "219191181110",
    name: "Top Road Black Jean MR107-5 Size 32",
    description: "A slim straight-fit black denim jean from Top Road's MR107-5 series in waist size 32. Crafted from durable denim with a clean black wash and tailored cut, this pair is ideal for both smart-casual and evening looks.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219191181110",
    tags: ["jeans", "black", "denim", "top road", "MR107", "size 32", "mens", "casual"],
  },
  {
    sku: "219191131110",
    name: "Fashion Brown Short Sleeve Shirt XXL 3XL",
    description: "A fashion-forward short-sleeve shirt in a rich brown tone, cut generously for plus sizes XXL and 3XL. Features a contemporary print and relaxed fit designed for style and comfort in larger proportions.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 1,
    barcode: "219191131110",
    tags: ["shirt", "brown", "short sleeve", "XXL", "3XL", "plus size", "fashion", "mens"],
  },
  {
    sku: "219191261110",
    name: "White & Brown Saint Dann Culture Shirts",
    description: "A premium short-sleeve shirt from Saint Dann Culture featuring a distinctive white and brown colorway. Known for its Afro-inspired artisan prints and quality craftsmanship, this shirt bridges contemporary fashion with cultural storytelling.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 4,
    barcode: "219191261110",
    tags: ["saint dann", "culture", "shirt", "white", "brown", "designer", "mens", "afro", "print"],
  },
  {
    sku: "219191101110",
    name: "Black Fuukeel Shirt XL",
    description: "A stylish black shirt from the Fuukeel label in size XL. Features clean lines and a refined cut that balances comfort with smart-casual elegance. A versatile addition to any contemporary men's wardrobe.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 1,
    barcode: "219191101110",
    tags: ["fuukeel", "shirt", "black", "XL", "mens", "casual", "designer"],
  },
  {
    sku: "219191091110",
    name: "Grey Fuukeel Shirt XXL",
    description: "A sophisticated grey shirt from Fuukeel in size XXL. The cool grey tone and precise tailoring make this an easy layering piece or standalone statement for everyday smart looks.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 1,
    barcode: "219191091110",
    tags: ["fuukeel", "shirt", "grey", "XXL", "mens", "casual", "designer"],
  },
  {
    sku: "219191081110",
    name: "White Fuukeel Shirt XXL",
    description: "A clean white shirt from Fuukeel in size XXL. Crisp, versatile, and well-constructed, this shirt works as a standalone smart-casual piece or as the foundation for a layered ensemble.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 1,
    barcode: "219191081110",
    tags: ["fuukeel", "shirt", "white", "XXL", "mens", "casual", "designer"],
  },
  {
    sku: "219191141110",
    name: "Fashion Dusty Blue Shirt 3XL 2XL",
    description: "A fashion-forward shirt in a muted dusty blue hue, available in oversized fits 2XL and 3XL. The subtle wash and contemporary cut make it a standout casual piece with an effortlessly cool edge.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 1,
    barcode: "219191141110",
    tags: ["shirt", "dusty blue", "2XL", "3XL", "fashion", "plus size", "mens", "casual"],
  },
  {
    sku: "219191331110",
    name: "Black With Blue Flowery Print Saint Dann Culture Shirts",
    description: "A vibrant Saint Dann Culture shirt combining a rich black base with intricate blue floral prints. Each shirt carries the brand's hallmark of culturally infused artisan design and premium woven fabric, making it a wearable piece of art.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 3,
    barcode: "219191331110",
    tags: ["saint dann", "culture", "shirt", "black", "blue", "floral", "print", "mens", "designer"],
  },
  {
    sku: "219191271110",
    name: "White Saint Dann Culture Shirts",
    description: "A pristine white short-sleeve shirt from Saint Dann Culture. Clean, refined, and culturally resonant, this crisp white option from the brand is versatile enough for casual days and smart social occasions alike.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 5,
    barcode: "219191271110",
    tags: ["saint dann", "culture", "shirt", "white", "designer", "mens", "clean"],
  },
  {
    sku: "219191281110",
    name: "Blue With White Spots Saint Dann Culture Shirts",
    description: "A striking Saint Dann Culture shirt in deep blue adorned with a distinctive white spot pattern. The bold contrast print delivers a playful yet polished look, staying true to the brand's culture-forward design ethos.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 5,
    barcode: "219191281110",
    tags: ["saint dann", "culture", "shirt", "blue", "white", "spots", "print", "mens", "designer"],
  },
  {
    sku: "219191291110",
    name: "Egyptian Print Saint Dann Culture Shirts",
    description: "A culturally rich Saint Dann Culture shirt featuring an Egyptian-inspired print. Drawing on ancient motifs and modern craftsmanship, this shirt is a bold fusion of heritage and contemporary style — a true statement piece.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 5,
    barcode: "219191291110",
    tags: ["saint dann", "culture", "shirt", "egyptian", "print", "heritage", "mens", "designer"],
  },
  {
    sku: "219191301110",
    name: "White Spotted Dusty Brown Saint Dann Culture Shirts",
    description: "A nuanced and earthy Saint Dann Culture shirt in dusty brown with a white spot overlay. The organic color palette and cultural print work together to create a refined, conversation-worthy piece for the discerning dresser.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 5,
    barcode: "219191301110",
    tags: ["saint dann", "culture", "shirt", "brown", "dusty", "white", "spots", "mens", "designer"],
  },
  {
    sku: "219191311110",
    name: "Beige Spotted Black Saint Dann Culture Shirts",
    description: "A sophisticated Saint Dann Culture shirt in warm beige with a black spot pattern. The subtle contrast creates a luxurious textural effect, while the brand's signature culturally inspired design keeps it distinctively unique.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 5,
    barcode: "219191311110",
    tags: ["saint dann", "culture", "shirt", "beige", "black", "spots", "mens", "designer"],
  },
  {
    sku: "219191321110",
    name: "White With Blue Flowery Print Saint Dann Culture Shirts",
    description: "A fresh and artistic Saint Dann Culture shirt on a white base with blue floral print accents. Lightweight and visually vibrant, this piece captures the brand's commitment to culturally expressive fashion.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 5,
    barcode: "219191321110",
    tags: ["saint dann", "culture", "shirt", "white", "blue", "floral", "print", "mens", "designer"],
  },
  {
    sku: "219191341110",
    name: "Golden Brown Saint Dann Culture Shirts",
    description: "A warm and opulent golden-brown shirt from Saint Dann Culture. The rich amber tone is elevated by the brand's signature culturally inspired detailing and premium fabric construction, making it perfect for evenings out or special occasions.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 85000,
    costPrice: 85000,
    stock: 5,
    barcode: "219191341110",
    tags: ["saint dann", "culture", "shirt", "golden", "brown", "mens", "designer", "warm"],
  },
  {
    sku: "219191411103",
    name: "Black D&G Shirt",
    description: "A classic all-black shirt from Dolce & Gabbana. Precision-tailored with the iconic D&G quality, this shirt exudes sleek Italian sophistication. A timeless wardrobe investment that pairs effortlessly with anything from jeans to formal trousers.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 170000,
    costPrice: 170000,
    stock: 6,
    barcode: "219191411103",
    tags: ["dolce gabbana", "d&g", "shirt", "black", "designer", "mens", "italian", "luxury"],
  },
  {
    sku: "219191211104",
    name: "Brown Long Sleeves Fendi Shirt XL 2XL 3XL",
    description: "A rich brown long-sleeve shirt from the iconic Italian luxury house Fendi. Available in sizes XL, 2XL, and 3XL, this shirt features the brand's superior fabric quality and refined tailoring, delivering effortless luxury in an earthy warm tone.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 125000,
    costPrice: 125000,
    stock: 3,
    barcode: "219191211104",
    tags: ["fendi", "shirt", "brown", "long sleeve", "designer", "mens", "luxury", "italian", "XL"],
  },
  {
    sku: "219192011100",
    name: "Black Loewe Shirt M L XL 2XL 3XL",
    description: "A sleek all-black shirt from the prestigious Spanish luxury house Loewe. Available in sizes M through 3XL, this shirt showcases the brand's commitment to refined minimalism and exceptional fabric quality. A cornerstone of the luxury minimalist wardrobe.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 170000,
    costPrice: 170000,
    stock: 5,
    barcode: "219192011100",
    tags: ["loewe", "shirt", "black", "designer", "mens", "luxury", "minimalist", "spanish"],
  },
  {
    sku: "219191911101",
    name: "Black Hermes T-Shirt With Orange Zipper M L XL 2XL 3XL",
    description: "A luxurious black T-shirt from Hermes featuring a distinctive orange zipper accent — a subtle nod to the brand's iconic colourway. Available in M to 3XL, this piece combines casual comfort with unmistakable high-fashion detailing.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 125000,
    costPrice: 125000,
    stock: 5,
    barcode: "219191911101",
    tags: ["hermes", "t-shirt", "black", "orange", "zipper", "designer", "mens", "luxury"],
  },
  {
    sku: "219191611109",
    name: "White Loro Piana Shirt S M L 2XL 3XL",
    description: "An ultra-premium white shirt from Loro Piana, the Italian master of fine fabrics. Available from S to 3XL, this shirt is crafted from the brand's extraordinarily soft and breathable woven fabric, offering unmatched comfort and understated luxury.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 165000,
    costPrice: 165000,
    stock: 6,
    barcode: "219191611109",
    tags: ["loro piana", "shirt", "white", "designer", "mens", "luxury", "italian", "premium"],
  },
  {
    sku: "219191511101",
    name: "Black Brunello Cucinelli Shirt S M L XL 2XL 3XL",
    description: "A refined black shirt from Brunello Cucinelli, the Italian master of quiet luxury. Available from S to 3XL, this piece embodies the brand's philosophy of understated elegance — impeccably crafted from premium fabric with subtle, sophisticated detailing.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 165000,
    costPrice: 165000,
    stock: 6,
    barcode: "219191511101",
    tags: ["brunello cucinelli", "shirt", "black", "designer", "mens", "luxury", "italian", "premium"],
  },
  {
    sku: "219191311100",
    name: "Beige Loro Piana Shirt S M L XL 2XL 3XL",
    description: "A timeless beige shirt from Loro Piana woven from the brand's signature premium fabric. Spanning sizes S to 3XL, this versatile shirt offers exceptional softness and a relaxed, elevated fit suited for both casual and smart-casual occasions.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 165000,
    costPrice: 165000,
    stock: 6,
    barcode: "219191311100",
    tags: ["loro piana", "shirt", "beige", "designer", "mens", "luxury", "italian", "premium"],
  },
  {
    sku: "219191111034",
    name: "Marco Donateli Dot Sleeve Corp Shirt L",
    description: "A distinctive corporate shirt from Marco Donateli featuring a polished dot-sleeve detail in size L. A refined smart-casual piece that balances Italian-inspired design with an approachable elegance, ideal for business and social events.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 95000,
    costPrice: 95000,
    stock: 2,
    barcode: "219191111034",
    tags: ["marco donateli", "shirt", "dot", "corporate", "mens", "designer", "L"],
  },
  {
    sku: "219198311101",
    name: "Black Round Neck With Faded Marks Write Up Behind XL",
    description: "A bold statement T-shirt in black featuring faded graphic marks and a signature write-up at the back, cut in size XL. A streetwear-inspired piece that blends artistic expression with relaxed urban style.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219198311101",
    tags: ["t-shirt", "black", "round neck", "graphic", "XL", "streetwear", "mens"],
  },
  {
    sku: "219198211107",
    name: "Black With Headset Logo Shirt 2XL",
    description: "A sleek black shirt in size 2XL featuring a minimalist headset logo graphic. Cool, understated, and modern — this piece appeals to the fashion-forward man who appreciates subtle branded detailing.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219198211107",
    tags: ["shirt", "black", "logo", "headset", "2XL", "graphic", "mens", "streetwear"],
  },
  {
    sku: "219198111103",
    name: "White Dot T-Shirt 4XL",
    description: "A clean white T-shirt adorned with an all-over dot pattern, cut in a generous 4XL for maximum comfort and style in plus-size proportions. Versatile and easy to style for everyday smart-casual wear.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219198111103",
    tags: ["t-shirt", "white", "dot", "4XL", "plus size", "mens", "casual"],
  },
  {
    sku: "219198011100",
    name: "Iini Brown T-Shirt 4XL",
    description: "A warm brown T-shirt from Iini in size 4XL. The earthy tone and comfortable oversized cut make this a relaxed yet stylish everyday essential for the larger-framed man.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219198011100",
    tags: ["iini", "t-shirt", "brown", "4XL", "plus size", "mens", "casual"],
  },
  {
    sku: "219197911104",
    name: "Black Jiil T-Shirt 4XL",
    description: "A bold black T-shirt from Jiil in size 4XL. Clean, confident, and perfectly proportioned for the plus-size wearer who wants to dress sharp without compromising comfort.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219197911104",
    tags: ["jiil", "t-shirt", "black", "4XL", "plus size", "mens", "casual"],
  },
  {
    sku: "219197811105",
    name: "Olive Green With White Stripe T-Shirt 3XL",
    description: "A relaxed T-shirt in earthy olive green with a contrasting white stripe detail, sized for 3XL. The tonal combination and casual silhouette make this an easy everyday piece with a sporty edge.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219197811105",
    tags: ["t-shirt", "olive", "green", "white", "stripe", "3XL", "plus size", "mens", "casual"],
  },
  {
    sku: "219197611101",
    name: "Iini Black T-Shirt 4XL",
    description: "A classic all-black T-shirt from Iini in a generous 4XL fit. Simple, premium, and comfortable — this versatile staple anchors any casual outfit for the plus-size man.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219197611101",
    tags: ["iini", "t-shirt", "black", "4XL", "plus size", "mens", "casual"],
  },

  // ───────────────────── T-SHIRTS ─────────────────────
  {
    sku: "219430811103",
    name: "FLX Male T-Shirt",
    description: "A comfortable and stylish FLX brand T-shirt for men. Constructed from soft, breathable fabric with a clean cut that suits a range of body types. A dependable everyday essential with a contemporary edge.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 3,
    barcode: "219430811103",
    tags: ["flx", "t-shirt", "mens", "casual", "everyday"],
  },
  {
    sku: "219430911103",
    name: "APT.9 White Male T-Shirt",
    description: "A clean and classic white T-shirt from APT.9. Known for quality basics, APT.9 delivers a well-fitted, premium cotton T-shirt that serves as the perfect foundation piece for any men's wardrobe.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 75000,
    costPrice: 75000,
    stock: 1,
    barcode: "219430911103",
    tags: ["apt.9", "t-shirt", "white", "mens", "basic", "casual"],
  },
  {
    sku: "219191541110",
    name: "Fashion T-Shirts",
    description: "A collection of fashion-forward T-shirts for the modern man. Featuring contemporary prints and cuts, these T-shirts are versatile enough for casual outings and styled looks alike.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 110000,
    costPrice: 110000,
    stock: 14,
    barcode: "219191541110",
    tags: ["t-shirt", "fashion", "mens", "casual", "print"],
  },
  {
    sku: "219191551110",
    name: "Fashion T-Shirts Long Sleeve",
    description: "A fashion-forward long-sleeve T-shirt for men. The extended sleeve adds versatility for cooler seasons or layered styling, making it a practical and stylish piece for the contemporary wardrobe.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 125000,
    costPrice: 125000,
    stock: 3,
    barcode: "219191551110",
    tags: ["t-shirt", "long sleeve", "fashion", "mens", "casual"],
  },
  {
    sku: "219191531110",
    name: "Button Down Shirt",
    description: "A clean and versatile button-down shirt for men. A wardrobe classic that transitions seamlessly from the office to casual outings, offering a neat silhouette and comfortable everyday fit.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 110000,
    costPrice: 110000,
    stock: 4,
    barcode: "219191531110",
    tags: ["shirt", "button down", "mens", "casual", "formal", "classic"],
  },
  {
    sku: "219191521110",
    name: "2and4 Net Shirt XXL XXXL",
    description: "A textured net-style shirt from 2and4 in oversized fits XXL and XXXL. The open-weave construction provides excellent breathability, making it ideal for warm weather while delivering a distinctly fashion-forward look.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 145000,
    costPrice: 145000,
    stock: 8,
    barcode: "219191521110",
    tags: ["2and4", "net shirt", "XXL", "XXXL", "plus size", "mens", "breathable"],
  },
  {
    sku: "219191511110",
    name: "Fashion Classic Shirt XXL",
    description: "A classic fashion shirt in a generous XXL cut. Clean lines, quality fabric, and timeless styling make this a dependable wardrobe piece for the modern man who prefers a refined everyday look.",
    category: "Mens Wear",
    subcategory: "Shirts",
    price: 125000,
    costPrice: 125000,
    stock: 3,
    barcode: "219191511110",
    tags: ["shirt", "classic", "fashion", "XXL", "mens", "casual"],
  },
  {
    sku: "219191441110",
    name: "Hermes Short Sleeve T-Shirt",
    description: "A premium short-sleeve T-shirt from Hermes, the iconic French luxury house. Crafted from superior cotton with impeccable detailing, this T-shirt delivers the brand's signature understated luxury in an effortlessly wearable form.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 65000,
    costPrice: 65000,
    stock: 8,
    barcode: "219191441110",
    tags: ["hermes", "t-shirt", "short sleeve", "designer", "mens", "luxury", "french"],
  },
  {
    sku: "219191371110",
    name: "White First Boys Club Sleeveless T-Shirt",
    description: "A sleek white sleeveless T-shirt from First Boys Club. Designed for the gym, layering, or warm-weather styling, this tank top features the brand's clean aesthetic with a comfortable, muscle-flattering cut.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 48500,
    costPrice: 48500,
    stock: 1,
    barcode: "219191371110",
    tags: ["first boys club", "sleeveless", "tank top", "white", "mens", "gym", "streetwear"],
  },
  {
    sku: "219191361110",
    name: "Purple First Boys Club Sleeveless T-Shirt",
    description: "A vibrant purple sleeveless T-shirt from First Boys Club. The bold color and athletic cut make this a striking choice for the gym, casual outings, or as a layering piece under a jacket.",
    category: "Mens Wear",
    subcategory: "T-Shirts",
    price: 48500,
    costPrice: 48500,
    stock: 1,
    barcode: "219191361110",
    tags: ["first boys club", "sleeveless", "tank top", "purple", "mens", "gym", "streetwear"],
  },

  // ───────────────────── POLO SHIRTS ─────────────────────
  {
    sku: "219194111072",
    name: "Brown Long Sleeve Sweater Polo L",
    description: "A luxurious brown long-sleeve sweater-style polo in size L. The sweater-like knit construction combined with the classic polo collar creates a sophisticated hybrid piece, ideal for smart-casual occasions in cooler weather.",
    category: "Mens Wear",
    subcategory: "Polo Shirts",
    price: 100000,
    costPrice: 100000,
    stock: 1,
    barcode: "219194111072",
    tags: ["polo", "sweater", "brown", "long sleeve", "mens", "smart casual", "knit", "L"],
  },
  {
    sku: "219191351110",
    name: "Polotgybpn Polo Shirt With Zip XL",
    description: "A modern polo shirt featuring a zip-up neckline in size XL. The zip detail adds a contemporary sportswear edge to the classic polo silhouette, making it a versatile piece for both casual and athletic occasions.",
    category: "Mens Wear",
    subcategory: "Polo Shirts",
    price: 100000,
    costPrice: 100000,
    stock: 1,
    barcode: "219191351110",
    tags: ["polo", "zip", "XL", "mens", "sporty", "casual"],
  },
  {
    sku: "219192311103",
    name: "Black D&G Polo Shirt M L XL 2XL 3XL",
    description: "A classic black polo shirt from Dolce & Gabbana. Available from M to 3XL, this polo shirt features the brand's iconic D&G emblem and impeccable Italian tailoring, delivering designer prestige in a relaxed, versatile format.",
    category: "Mens Wear",
    subcategory: "Polo Shirts",
    price: 125000,
    costPrice: 125000,
    stock: 4,
    barcode: "219192311103",
    tags: ["dolce gabbana", "d&g", "polo", "black", "designer", "mens", "luxury", "italian"],
  },
  {
    sku: "219192411101",
    name: "Navy Blue Loro Piana Polo Shirt M L XL 2XL 3XL",
    description: "An exquisite navy blue polo shirt from Loro Piana, woven from the brand's signature premium fabric. Available M to 3XL, this polo is the epitome of refined casual dressing — understated, supremely comfortable, and unmistakably luxurious.",
    category: "Mens Wear",
    subcategory: "Polo Shirts",
    price: 145000,
    costPrice: 145000,
    stock: 4,
    barcode: "219192411101",
    tags: ["loro piana", "polo", "navy blue", "designer", "mens", "luxury", "italian", "premium"],
  },
  {
    sku: "219192211100",
    name: "D&G Milk Color Polo Shirt M L XL 2XL 3XL",
    description: "A sophisticated milk-white polo shirt from Dolce & Gabbana. Available in sizes M to 3XL, this polo features the brand's signature craftsmanship and the D&G logo, delivering designer elegance in a clean, versatile tone.",
    category: "Mens Wear",
    subcategory: "Polo Shirts",
    price: 125000,
    costPrice: 125000,
    stock: 5,
    barcode: "219192211100",
    tags: ["dolce gabbana", "d&g", "polo", "milk", "cream", "white", "designer", "mens", "luxury"],
  },

  // ───────────────────── TRADITIONAL WEAR ─────────────────────
  {
    sku: "219141011101",
    name: "Jalabiya",
    description: "A classic traditional Jalabiya robe, a timeless garment of cultural elegance. Flowing, comfortable, and dignified, this Jalabiya is ideal for religious occasions, cultural celebrations, and relaxed home wear. Crafted from quality fabric for lasting comfort.",
    category: "Mens Wear",
    subcategory: "Traditional Wear",
    price: 47000,
    costPrice: 47000,
    stock: 13,
    barcode: "219141011101",
    tags: ["jalabiya", "traditional", "robe", "cultural", "mens", "african", "islamic"],
  },

  // ───────────────────── ACCESSORIES ─────────────────────
  {
    sku: "219191241110",
    name: "Colorful Shining Ribbon Bag",
    description: "A vibrant and eye-catching ribbon bag with a colorful shining finish. A playful and stylish accessory for men who like to add a pop of color and personality to their look.",
    category: "Mens Wear",
    subcategory: "Accessories",
    price: 25000,
    costPrice: 25000,
    stock: 2,
    barcode: "219191241110",
    tags: ["bag", "ribbon", "colorful", "shining", "accessory", "mens", "fashion"],
  },
  {
    sku: "219193111045",
    name: "Male Hand Band",
    description: "A stylish wristband / hand band accessory for men. A subtle yet impactful fashion accessory that adds a sporty or streetwear flair to any outfit. Available in generous quantity.",
    category: "Mens Wear",
    subcategory: "Accessories",
    price: 35000,
    costPrice: 35000,
    stock: 20,
    barcode: "219193111045",
    tags: ["hand band", "wristband", "accessory", "mens", "sporty", "streetwear"],
  },
  {
    sku: "219191501110",
    name: "Calvin Klein Socks",
    description: "Premium men's socks from the iconic American brand Calvin Klein. Crafted from a soft cotton blend for everyday comfort, with the brand's signature logo ribbed into the cuff for a touch of designer refinement.",
    category: "Mens Wear",
    subcategory: "Accessories",
    price: 60000,
    costPrice: 60000,
    stock: 2,
    barcode: "219191501110",
    tags: ["calvin klein", "socks", "designer", "mens", "accessories", "cotton"],
  },
  {
    sku: "219191491110",
    name: "Gucci Socks",
    description: "Luxury men's socks from the iconic Italian house Gucci. Featuring the brand's signature styling and premium fabric construction, these socks are a sophisticated detail that elevates even the most casual outfit from the ground up.",
    category: "Mens Wear",
    subcategory: "Accessories",
    price: 60000,
    costPrice: 60000,
    stock: 2,
    barcode: "219191491110",
    tags: ["gucci", "socks", "designer", "mens", "accessories", "luxury", "italian"],
  },
  {
    sku: "219191481110",
    name: "Louis Vuitton Briefs",
    description: "Premium men's briefs from the iconic French luxury house Louis Vuitton. Crafted from a soft, breathable fabric blend with the brand's signature design accents, these briefs offer superior comfort with unmistakable luxury.",
    category: "Mens Wear",
    subcategory: "Accessories",
    price: 55000,
    costPrice: 55000,
    stock: 2,
    barcode: "219191481110",
    tags: ["louis vuitton", "lv", "briefs", "underwear", "designer", "mens", "luxury", "french"],
  },
  {
    sku: "219191471110",
    name: "Pierre Cardin Briefs",
    description: "Classic men's briefs from the legendary French fashion designer Pierre Cardin. Constructed for lasting comfort and a perfect fit, these briefs feature the brand's clean design and quality fabric — everyday luxury at an accessible price.",
    category: "Mens Wear",
    subcategory: "Accessories",
    price: 50000,
    costPrice: 50000,
    stock: 6,
    barcode: "219191471110",
    tags: ["pierre cardin", "briefs", "underwear", "designer", "mens", "french", "classic"],
  },
  {
    sku: "219191461110",
    name: "Zegna Briefs",
    description: "Men's briefs from the prestigious Italian luxury brand Ermenegildo Zegna. Made from the brand's signature premium fabric, these briefs offer an exceptional level of softness and fit — a luxurious foundation to any outfit.",
    category: "Mens Wear",
    subcategory: "Accessories",
    price: 50000,
    costPrice: 50000,
    stock: 2,
    barcode: "219191461110",
    tags: ["zegna", "ermenegildo zegna", "briefs", "underwear", "designer", "mens", "luxury", "italian"],
  },
  {
    sku: "219191451110",
    name: "Loro Piana Briefs",
    description: "Luxury men's briefs from Loro Piana, crafted from the brand's extraordinarily fine fabric. These briefs set the standard for intimate luxury — incredibly soft, perfectly fitted, and bearing the prestige of one of Italy's finest textile houses.",
    category: "Mens Wear",
    subcategory: "Accessories",
    price: 55000,
    costPrice: 55000,
    stock: 4,
    barcode: "219191451110",
    tags: ["loro piana", "briefs", "underwear", "designer", "mens", "luxury", "italian", "premium"],
  },

  // ───────────────────── TROUSERS ─────────────────────
  {
    sku: "219199211102",
    name: "Finelong Black Waist Band Pant Size 38 40",
    description: "A smart Finelong black trouser with a distinctive elasticated waist band, available in sizes 38 and 40. The sleek black fabric and tailored cut make these trousers an elegant option for both formal and smart-casual occasions.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219199211102",
    tags: ["finelong", "trousers", "black", "waist band", "size 38", "size 40", "mens", "formal"],
  },
  {
    sku: "219199511106",
    name: "Finelong Black Slim Waist Pant Size 40 38",
    description: "A sleek Finelong slim-fit black trouser with a refined waist finish, available in sizes 38 and 40. The slim silhouette and quality construction make these a sharp choice for formal occasions and smart everyday dressing.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219199511106",
    tags: ["finelong", "trousers", "black", "slim", "size 38", "size 40", "mens", "formal"],
  },
  {
    sku: "219199411100",
    name: "Finelong Blue Big Waist Band Pant Size 40 38",
    description: "A stylish Finelong blue trouser featuring a prominent waist band detail, available in sizes 38 and 40. The rich blue tone and structured silhouette make these an excellent statement trouser for smart or formal dressing.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 70000,
    costPrice: 70000,
    stock: 2,
    barcode: "219199411100",
    tags: ["finelong", "trousers", "blue", "waist band", "size 38", "size 40", "mens", "formal"],
  },
  {
    sku: "219196711109",
    name: "Black Pant Slim Hand Size 42",
    description: "A tailored slim-fit black trouser with a slim hand-finished waist, in size 42. Clean lines and a streamlined fit make this a versatile formal and smart-casual staple.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 75000,
    costPrice: 75000,
    stock: 1,
    barcode: "219196711109",
    tags: ["trousers", "black", "slim", "size 42", "mens", "formal", "tailored"],
  },
  {
    sku: "219196511105",
    name: "Black Pant Slim Hand Size 38",
    description: "A sleek slim-fit black trouser with a polished hand-finished waist in size 38. The precise cut and clean finish make these a go-to option for formal events or elevated everyday styling.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 75000,
    costPrice: 75000,
    stock: 1,
    barcode: "219196511105",
    tags: ["trousers", "black", "slim", "size 38", "mens", "formal", "tailored"],
  },
  {
    sku: "219196911107",
    name: "Black Pant Slim Hand & Metal Hold Size 44",
    description: "A premium slim-fit black trouser with a hand-finished waist and metal clasp closure in size 44. The metal hardware adds a luxurious finishing touch to an already sharp and impeccably tailored silhouette.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 80000,
    costPrice: 80000,
    stock: 1,
    barcode: "219196911107",
    tags: ["trousers", "black", "slim", "metal hold", "size 44", "mens", "formal", "tailored"],
  },
  {
    sku: "219196811109",
    name: "Grey Pant Slim Hand Size 36",
    description: "A refined slim-fit grey trouser with a hand-finished waist in size 36. The neutral grey tone and clean cut make these a highly versatile trouser that works equally well for formal and smart-casual occasions.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 75000,
    costPrice: 75000,
    stock: 1,
    barcode: "219196811109",
    tags: ["trousers", "grey", "slim", "size 36", "mens", "formal", "tailored"],
  },
  {
    sku: "219197011108",
    name: "Navy Blue Slim Band Pant Size 40",
    description: "A sharp navy blue slim-band trouser in size 40. The classic navy hue and streamlined fit make these an essential piece for formal dressing and elevated smart-casual looks.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 75000,
    costPrice: 75000,
    stock: 1,
    barcode: "219197011108",
    tags: ["trousers", "navy blue", "slim", "size 40", "mens", "formal", "tailored"],
  },
  {
    sku: "219199311100",
    name: "Finelong Grey Waist Band Pant Size 38",
    description: "A smart Finelong grey trouser with a defined waist band in size 38. The clean grey fabric and structured waist create a polished look suitable for formal wear and professional settings.",
    category: "Mens Wear",
    subcategory: "Trousers",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219199311100",
    tags: ["finelong", "trousers", "grey", "waist band", "size 38", "mens", "formal"],
  },

  // ───────────────────── JEANS ─────────────────────
  {
    sku: "219191071110",
    name: "Dark Blue Jean MR110-3 Size 36 38 40",
    description: "A straight-fit dark blue wash denim from the MR110-3 series, available in waist sizes 36, 38, and 40. The deep indigo wash and clean-cut silhouette offer a versatile, timeless look from casual to smart-casual occasions.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 8,
    barcode: "219191071110",
    tags: ["jeans", "dark blue", "denim", "MR110", "size 36", "size 38", "size 40", "mens", "straight fit"],
  },
  {
    sku: "219191061110",
    name: "Blue Jean MR110-2 Size 36 38 40",
    description: "A slim straight-fit medium blue denim from the MR110-2 series, available in waist sizes 36, 38, and 40. The classic mid-wash and comfortable fit make this a reliable everyday denim staple.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 8,
    barcode: "219191061110",
    tags: ["jeans", "blue", "denim", "MR110", "size 36", "size 38", "size 40", "mens", "slim fit"],
  },
  {
    sku: "219191401110",
    name: "Gallery Dept Male Jeans",
    description: "Artisan-distressed denim jeans from Gallery Dept, the LA-based fashion label known for hand-crafted, one-of-a-kind pieces. Each pair carries the brand's signature painted and bleached detailing, making it a wearable work of art for the discerning streetwear collector.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 70000,
    costPrice: 70000,
    stock: 4,
    barcode: "219191401110",
    tags: ["gallery dept", "jeans", "denim", "distressed", "streetwear", "designer", "mens", "LA"],
  },
  {
    sku: "219191391110",
    name: "Amiri Male Jeans",
    description: "Premium denim jeans from Amiri, the Los Angeles luxury label. Featuring the brand's signature rock-luxe detailing — whether distressed finishes or bold hardware — these jeans deliver high-fashion attitude with a perfectly tailored fit.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 70000,
    costPrice: 70000,
    stock: 4,
    barcode: "219191391110",
    tags: ["amiri", "jeans", "denim", "luxury", "designer", "mens", "rock", "LA"],
  },
  {
    sku: "219191381110",
    name: "Purple Brand Jeans",
    description: "Premium denim jeans from Purple Brand, the luxury streetwear label known for its distinctive distressed and painted denim. These jeans combine superior Japanese denim construction with bold artistic detailing, creating an instant statement piece.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 70000,
    costPrice: 70000,
    stock: 6,
    barcode: "219191381110",
    tags: ["purple brand", "jeans", "denim", "luxury", "streetwear", "designer", "mens", "distressed"],
  },
  {
    sku: "219196111106",
    name: "Black Jean MR110-4 Size 33",
    description: "A slim straight-fit black denim from the MR110-4 series in waist size 33. The clean black wash and precise cut deliver a polished, versatile look that works across casual and smart-casual occasions.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219196111106",
    tags: ["jeans", "black", "denim", "MR110", "size 33", "mens", "slim fit"],
  },
  {
    sku: "219196011108",
    name: "Black Jean MR110-4 Size 32",
    description: "A slim straight-fit black denim from the MR110-4 series in waist size 32. Crisp black wash and a clean tailored cut create a versatile everyday jean that pairs with everything in the wardrobe.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219196011108",
    tags: ["jeans", "black", "denim", "MR110", "size 32", "mens", "slim fit"],
  },
  {
    sku: "219195911106",
    name: "Black Jean MR110-4 Size 31",
    description: "A slim straight-fit black denim from the MR110-4 series in waist size 31. A sharp, no-fuss jean in a clean black wash for the slimmer-framed man who values a tailored look.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219195911106",
    tags: ["jeans", "black", "denim", "MR110", "size 31", "mens", "slim fit"],
  },
  {
    sku: "219195811101",
    name: "Black Jean MR110-4 Size 30",
    description: "A slim straight-fit black denim from the MR110-4 series in waist size 30. The smallest in the series, offering a sharp, close-fitting cut in a clean black wash for a sleek and modern silhouette.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219195811101",
    tags: ["jeans", "black", "denim", "MR110", "size 30", "mens", "slim fit"],
  },
  {
    sku: "219196311103",
    name: "Black Jean MR110-4 Size 36",
    description: "A slim straight-fit black denim from the MR110-4 series in waist size 36. Clean, versatile, and well-constructed for comfortable all-day wear with a consistently sharp silhouette.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219196311103",
    tags: ["jeans", "black", "denim", "MR110", "size 36", "mens", "slim fit"],
  },
  {
    sku: "219196211100",
    name: "Black Jean MR110-4 Size 34",
    description: "A slim straight-fit black denim from the MR110-4 series in waist size 34. Classic black wash with a clean, versatile cut — an essential denim for the well-dressed man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219196211100",
    tags: ["jeans", "black", "denim", "MR110", "size 34", "mens", "slim fit"],
  },
  {
    sku: "219195711106",
    name: "Dark Blue Jean Top Road MR107-4 Size 42",
    description: "A straight-fit dark blue denim from Top Road's MR107-4 series in waist size 42. The deep indigo wash and relaxed straight cut are ideal for the man seeking a polished, dependable denim in a generous fit.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219195711106",
    tags: ["top road", "jeans", "dark blue", "denim", "MR107", "size 42", "mens", "straight fit"],
  },
  {
    sku: "219195511102",
    name: "Dark Blue Jean Top Road MR107-4 Size 38",
    description: "A straight-fit dark blue denim from Top Road's MR107-4 series in waist size 38. The rich indigo wash and reliable cut make this a go-to everyday denim for the sharp-dressing man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219195511102",
    tags: ["top road", "jeans", "dark blue", "denim", "MR107", "size 38", "mens", "straight fit"],
  },
  {
    sku: "219195411106",
    name: "Dark Blue Jean Top Road MR107-4 Size 36",
    description: "A slim straight-fit dark blue denim from Top Road's MR107-4 series in waist size 36. The deep indigo wash and tailored cut deliver a polished look across casual and smart-casual settings.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 3,
    barcode: "219195411106",
    tags: ["top road", "jeans", "dark blue", "denim", "MR107", "size 36", "mens", "slim fit"],
  },
  {
    sku: "219195311100",
    name: "Dark Blue Jean Top Road MR107-4 Size 34",
    description: "A slim straight-fit dark blue denim from Top Road's MR107-4 series in waist size 34. The dark indigo wash and precise fit give these jeans a versatile, smart-casual edge suitable for a wide range of occasions.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219195311100",
    tags: ["top road", "jeans", "dark blue", "denim", "MR107", "size 34", "mens", "slim fit"],
  },
  {
    sku: "219195211107",
    name: "Dark Blue Jean Top Road MR107-4 Size 32",
    description: "A slim straight-fit dark blue denim from Top Road's MR107-4 series in waist size 32. Crisp dark wash and a slim-fitting cut for the leaner-framed man who wants a polished everyday denim.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219195211107",
    tags: ["top road", "jeans", "dark blue", "denim", "MR107", "size 32", "mens", "slim fit"],
  },
  {
    sku: "219195111100",
    name: "Dark Blue Jean Top Road MR107-4 Size 30",
    description: "A slim straight-fit dark blue denim from Top Road's MR107-4 series in waist size 30. A sleek, narrow-cut option in deep indigo wash for the slimmer-framed man who favours a tailored silhouette.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219195111100",
    tags: ["top road", "jeans", "dark blue", "denim", "MR107", "size 30", "mens", "slim fit"],
  },
  {
    sku: "219195011100",
    name: "Black Jean Top Road MR107-6 Size 42",
    description: "A straight-fit black denim from Top Road's MR107-6 series in waist size 42. The clean black wash and comfortable straight cut make this a dependable denim option for the larger-framed man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219195011100",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 42", "mens", "straight fit"],
  },
  {
    sku: "219194911106",
    name: "Black Jean Top Road MR107-6 Size 40",
    description: "A straight-fit black denim from Top Road's MR107-6 series in waist size 40. A reliable, versatile black jean with a clean wash and structured cut for everyday smart-casual wear.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219194911106",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 40", "mens", "straight fit"],
  },
  {
    sku: "219194811101",
    name: "Black Jean Top Road MR107-6 Size 38",
    description: "A slim straight-fit black denim from Top Road's MR107-6 series in waist size 38. The smooth black finish and precise cut make these a sharp, go-to option for daily smart-casual styling.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219194811101",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 38", "mens", "slim fit"],
  },
  {
    sku: "219194711100",
    name: "Black Jean Top Road MR107-6 Size 36",
    description: "A slim straight-fit black denim from Top Road's MR107-6 series in waist size 36. Clean black wash with a tailored fit — a versatile wardrobe staple for the fashion-conscious man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 3,
    barcode: "219194711100",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 36", "mens", "slim fit"],
  },
  {
    sku: "219194611104",
    name: "Black Jean Top Road MR107-6 Size 34",
    description: "A slim straight-fit black denim from Top Road's MR107-6 series in waist size 34. Precise cut, clean black wash, and durable denim construction for a reliable everyday jean.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219194611104",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 34", "mens", "slim fit"],
  },
  {
    sku: "219194511100",
    name: "Black Jean Top Road MR107-6 Size 32",
    description: "A slim straight-fit black denim from Top Road's MR107-6 series in waist size 32. A sharply tailored, slim-profile black jean for the leaner-framed man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219194511100",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 32", "mens", "slim fit"],
  },
  {
    sku: "219194411106",
    name: "Black Jean Top Road MR107-6 Size 30",
    description: "A slim straight-fit black denim from Top Road's MR107-6 series in waist size 30. A slender-cut, clean black denim for the slim-framed man seeking a precise and modern silhouette.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219194411106",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 30", "mens", "slim fit"],
  },
  {
    sku: "219194311107",
    name: "Blue Jean Top Road MR107-2 Size 42",
    description: "A classic straight-fit blue denim from Top Road's MR107-2 series in waist size 42. The clean mid-blue wash and relaxed straight cut offer a versatile, timeless look for the larger-framed man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219194311107",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 42", "mens", "straight fit"],
  },
  {
    sku: "219194211102",
    name: "Blue Jean Top Road MR107-2 Size 40",
    description: "A straight-fit blue denim from Top Road's MR107-2 series in waist size 40. A reliable, well-constructed mid-wash jean with a clean silhouette for everyday casual and smart-casual wear.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219194211102",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 40", "mens", "straight fit"],
  },
  {
    sku: "219194111106",
    name: "Blue Jean Top Road MR107-2 Size 38",
    description: "A slim straight-fit blue denim from Top Road's MR107-2 series in waist size 38. Mid-wash blue and a tailored cut deliver a clean, everyday look with a smart-casual edge.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219194111106",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 38", "mens", "slim fit"],
  },
  {
    sku: "219194011106",
    name: "Blue Jean Top Road MR107-2 Size 36",
    description: "A slim straight-fit blue denim from Top Road's MR107-2 series in waist size 36. A go-to everyday denim in a classic mid-blue wash with a reliable, versatile fit.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 3,
    barcode: "219194011106",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 36", "mens", "slim fit"],
  },
  {
    sku: "219193911103",
    name: "Blue Jean Top Road MR107-2 Size 34",
    description: "A slim straight-fit blue denim from Top Road's MR107-2 series in waist size 34. Clean mid-blue wash and precise tailoring for a sharp everyday jean suited to both casual and smart-casual wear.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219193911103",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 34", "mens", "slim fit"],
  },
  {
    sku: "219193811103",
    name: "Blue Jean Top Road MR107-2 Size 32",
    description: "A slim straight-fit blue denim from Top Road's MR107-2 series in waist size 32. A well-fitting mid-blue denim for the slimmer man who wants a clean, polished look.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219193811103",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 32", "mens", "slim fit"],
  },
  {
    sku: "219193711100",
    name: "Blue Jean Top Road MR107-2 Size 30",
    description: "A slim straight-fit blue denim from Top Road's MR107-2 series in waist size 30. A narrow-cut, classic mid-blue denim for the slim-framed man seeking a tailored everyday jean.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219193711100",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 30", "mens", "slim fit"],
  },
  {
    sku: "219193511105",
    name: "Blue Jean Top Road MR107-1 Size 40",
    description: "A classic straight-fit blue denim from Top Road's MR107-1 series in waist size 40. A clean medium-wash jean with a reliable, comfortable fit for the larger-framed man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219193511105",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 40", "mens", "straight fit"],
  },
  {
    sku: "219193411107",
    name: "Blue Jean Top Road MR107-1 Size 38",
    description: "A slim straight-fit blue denim from Top Road's MR107-1 series in waist size 38. The clean medium-blue wash and versatile cut make this an everyday wardrobe staple.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219193411107",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 38", "mens", "slim fit"],
  },
  {
    sku: "219193311109",
    name: "Blue Jean Top Road MR107-1 Size 36",
    description: "A slim straight-fit blue denim from Top Road's MR107-1 series in waist size 36. A dependable everyday denim in a clean medium-blue wash with a comfortable, tailored fit.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 3,
    barcode: "219193311109",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 36", "mens", "slim fit"],
  },
  {
    sku: "219193211108",
    name: "Blue Jean Top Road MR107-1 Size 34",
    description: "A slim straight-fit blue denim from Top Road's MR107-1 series in waist size 34. Clean medium-blue wash and a slim-fit cut for a sharp, versatile everyday look.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219193211108",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 34", "mens", "slim fit"],
  },
  {
    sku: "219193111102",
    name: "Blue Jean Top Road MR107-1 Size 32",
    description: "A slim straight-fit blue denim from Top Road's MR107-1 series in waist size 32. Precise cut and clean medium-blue wash for the slimmer-framed man who values a tailored silhouette.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219193111102",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 32", "mens", "slim fit"],
  },
  {
    sku: "219193011100",
    name: "Blue Jean Top Road MR107-1 Size 30",
    description: "A slim straight-fit blue denim from Top Road's MR107-1 series in waist size 30. A slender-cut classic denim in medium-blue wash for the slim-framed man seeking a clean everyday jean.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219193011100",
    tags: ["top road", "jeans", "blue", "denim", "MR107", "size 30", "mens", "slim fit"],
  },
  {
    sku: "219192811103",
    name: "Top Road Black Jean MR107-5 Size 38",
    description: "A slim straight-fit black denim from Top Road's MR107-5 series in waist size 38. Clean black wash and a structured cut deliver a sharp, everyday option in classic black denim.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 6500,
    costPrice: 6500,
    stock: 2,
    barcode: "219192811103",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 38", "mens", "slim fit"],
  },
  {
    sku: "219192711102",
    name: "Top Road Black Jean MR107-5 Size 36",
    description: "A slim straight-fit black denim from Top Road's MR107-5 series in waist size 36. The clean black wash and tailored fit make these a versatile, sharply styled everyday denim.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 3,
    barcode: "219192711102",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 36", "mens", "slim fit"],
  },
  {
    sku: "219192611105",
    name: "Top Road Black Jean MR107-5 Size 34",
    description: "A slim straight-fit black denim from Top Road's MR107-5 series in waist size 34. Clean, precise, and perfectly tailored — a dependable everyday black jean.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 2,
    barcode: "219192611105",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 34", "mens", "slim fit"],
  },
  {
    sku: "219192511100",
    name: "Top Road Black Jean MR107-5 Size 30",
    description: "A slim straight-fit black denim from Top Road's MR107-5 series in waist size 30. A clean black-wash jean with a slender, close-fitting cut for the slim-framed man.",
    category: "Mens Wear",
    subcategory: "Jeans",
    price: 65000,
    costPrice: 65000,
    stock: 1,
    barcode: "219192511100",
    tags: ["top road", "jeans", "black", "denim", "MR107", "size 30", "mens", "slim fit"],
  },

  // ───────────────────── SUITS & SETS ─────────────────────
  {
    sku: "219197311100",
    name: "USD Black Single Button 3-Piece Suit Set Size 58-42 54-38",
    description: "A commanding 3-piece suit from USD in deep black, featuring a refined single-button closure. Available in sizes 58/42 and 54/38, this tailored ensemble — jacket, trousers, and waistcoat — is built for the man who demands sharp, authoritative dressing at formal events.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 220000,
    costPrice: 220000,
    stock: 2,
    barcode: "219197311100",
    tags: ["usd", "suit", "3 piece", "black", "single button", "formal", "tailored", "mens", "size 58", "size 42"],
  },
  {
    sku: "219198811105",
    name: "Blue UZD Suit Set Size 58-42 44-34",
    description: "A distinguished blue suit set from UZD, available in sizes 58/42 and 44/34. Tailored for a structured, confident silhouette, this suit delivers polish and presence for formal events, business meetings, and special occasions.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 180000,
    costPrice: 180000,
    stock: 2,
    barcode: "219198811105",
    tags: ["uzd", "suit", "blue", "formal", "tailored", "mens", "size 58", "size 44"],
  },
  {
    sku: "219197511107",
    name: "USD White Blazer & Black Pant Set Size 58 Size 56",
    description: "A bold and elegant suit set from USD pairing a pristine white blazer with sharp black trousers. Available in sizes 56 and 58, this combination creates a striking formal look with high-contrast drama — ideal for weddings, galas, and milestone events.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 300000,
    costPrice: 300000,
    stock: 2,
    barcode: "219197511107",
    tags: ["usd", "suit", "white blazer", "black pant", "formal", "tailored", "mens", "size 56", "size 58"],
  },
  {
    sku: "219197111100",
    name: "USD Grey & Pink Striped Sit Set Double Breasted 58-42",
    description: "A sophisticated double-breasted suit set from USD in elegant grey with subtle pink stripes, tailored in size 58/42. The double-breasted closure adds authority and old-world elegance, making this a commanding choice for formal occasions.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 165000,
    costPrice: 165000,
    stock: 1,
    barcode: "219197111100",
    tags: ["usd", "suit", "grey", "pink", "striped", "double breasted", "formal", "tailored", "mens"],
  },
  {
    sku: "219197211105",
    name: "Navy Blue Stylish Suit Set With Flank Size 56-40",
    description: "A sleek and modern navy blue suit set featuring a distinctive flank detail, in size 56/40. The deep navy tone and sculpted cut create a powerful, fashion-forward formal silhouette for the style-conscious professional.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 200000,
    costPrice: 200000,
    stock: 1,
    barcode: "219197211105",
    tags: ["suit", "navy blue", "flank", "formal", "tailored", "mens", "stylish", "size 56"],
  },
  {
    sku: "219197411109",
    name: "Light Blue Single Button Suit Set Size 44-34",
    description: "A crisp light blue single-button suit set in size 44/34. The soft blue hue and clean single-button closure deliver a fresh, refined formal look — perfect for weddings, corporate events, and special occasions in warmer seasons.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 180000,
    costPrice: 180000,
    stock: 1,
    barcode: "219197411109",
    tags: ["suit", "light blue", "single button", "formal", "tailored", "mens", "size 44"],
  },
  {
    sku: "219199011109",
    name: "UZD Bronze Suit Set Size 6-40",
    description: "A distinctive bronze suit set from UZD that makes a bold and opulent statement at formal events. The warm metallic bronze tone is expertly tailored for a rich, eye-catching silhouette that commands every room.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 180000,
    costPrice: 180000,
    stock: 1,
    barcode: "219199011109",
    tags: ["uzd", "suit", "bronze", "formal", "tailored", "mens", "metallic"],
  },
  {
    sku: "219198911101",
    name: "Plain Light Blue Suit Set White Line Pocket Size 46",
    description: "A sharp light blue suit set with a distinctive white-lined pocket detail in size 46. The clean contrast between the soft blue fabric and the bright white pocket trim creates an elegant, distinctive formal look.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 180000,
    costPrice: 180000,
    stock: 1,
    barcode: "219198911101",
    tags: ["suit", "light blue", "white", "formal", "tailored", "mens", "size 46"],
  },
  {
    sku: "219199111100",
    name: "UZD Grey & Blue Tiny Striped Suit Set Size 54-38",
    description: "A refined grey and blue tonal pin-striped suit set from UZD in size 54/38. The subtle micro-stripe pattern adds depth and visual interest to an already polished silhouette, making it a sophisticated choice for formal and business settings.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 165000,
    costPrice: 165000,
    stock: 1,
    barcode: "219199111100",
    tags: ["uzd", "suit", "grey", "blue", "striped", "formal", "tailored", "mens", "size 54"],
  },

  // ───────────────────── BLAZERS ─────────────────────
  {
    sku: "219197111092",
    name: "Finelong Plain Black Suit With White Laced Pocket XL 2XL",
    description: "An elegant Finelong plain black suit featuring a refined white laced pocket detail, available in sizes XL and 2XL. The stark black fabric contrasted by the intricate white lace trim delivers a bold and distinctive formal elegance.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 180000,
    costPrice: 180000,
    stock: 1,
    barcode: "219197111092",
    tags: ["finelong", "suit", "black", "white lace", "pocket", "formal", "tailored", "mens", "XL", "2XL"],
  },
  {
    sku: "219199911108",
    name: "Finelong Royal Blue Blazer 2 Button L XL 2XL",
    description: "A distinguished royal blue two-button blazer from Finelong, available in sizes L, XL, and 2XL. The vibrant royal blue hue is expertly tailored for a structured, commanding silhouette that works beautifully for formal and smart-casual occasions.",
    category: "Mens Wear",
    subcategory: "Blazers",
    price: 120000,
    costPrice: 120000,
    stock: 3,
    barcode: "219199911108",
    tags: ["finelong", "blazer", "royal blue", "2 button", "formal", "mens", "tailored", "L", "XL", "2XL"],
  },
  {
    sku: "219191001110",
    name: "Finelong Royal Blue Suit Set L XL XXL",
    description: "A complete royal blue suit set from Finelong, available in sizes L, XL, and XXL. Impeccably tailored in a rich blue fabric with a structured silhouette, this suit set is a bold and polished choice for weddings, formal events, and important occasions.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 180000,
    costPrice: 180000,
    stock: 3,
    barcode: "219191001110",
    tags: ["finelong", "suit", "royal blue", "formal", "tailored", "mens", "L", "XL", "XXL"],
  },
  {
    sku: "219199711101",
    name: "Finelong Ash Tiny Striped Double Breasted Suit XL XXXL",
    description: "A distinguished double-breasted suit from Finelong in a refined ash grey with a subtle micro-stripe pattern, available in sizes XL and XXXL. The double-breasted silhouette and classic striping combine for a look of traditional tailoring authority.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 160000,
    costPrice: 160000,
    stock: 2,
    barcode: "219199711101",
    tags: ["finelong", "suit", "ash", "grey", "striped", "double breasted", "formal", "mens", "XL", "XXXL"],
  },
  {
    sku: "219199811107",
    name: "Finelong Sky Blue Striped White Line Pocket Blazer XXL",
    description: "A striking sky blue blazer from Finelong featuring a pinstripe pattern and a refined white-lined pocket detail, in size XXL. The fresh blue tone and crisp white accents deliver a distinctive formal look full of personality and elegance.",
    category: "Mens Wear",
    subcategory: "Blazers",
    price: 165000,
    costPrice: 165000,
    stock: 2,
    barcode: "219199811107",
    tags: ["finelong", "blazer", "sky blue", "striped", "white", "pocket", "formal", "mens", "XXL"],
  },
  {
    sku: "219199611108",
    name: "Bytom Suede Blazer",
    description: "A luxurious suede-finish blazer from Bytom, the distinguished Polish tailoring house. The rich texture and premium fabric construction deliver an elevated smart-casual aesthetic — perfect for the man who values tactile luxury in his wardrobe.",
    category: "Mens Wear",
    subcategory: "Blazers",
    price: 105000,
    costPrice: 105000,
    stock: 2,
    barcode: "219199611108",
    tags: ["bytom", "blazer", "suede", "designer", "mens", "smart casual", "premium", "polish"],
  },
  {
    sku: "219198711105",
    name: "Zara Man Royal Blue Bold Striped Blazer Size 54",
    description: "A bold statement blazer from Zara Man in a vibrant royal blue with wide, striking stripes, in size 54. The dramatic stripe pattern and confident cut make this a head-turning choice for events where standing out is the goal.",
    category: "Mens Wear",
    subcategory: "Blazers",
    price: 125000,
    costPrice: 125000,
    stock: 1,
    barcode: "219198711105",
    tags: ["zara", "blazer", "royal blue", "striped", "bold", "mens", "size 54", "formal"],
  },
  {
    sku: "219191111106",
    name: "Finelong Navy Blue Blazer With Striped Pocket L 2XL",
    description: "A sharp Finelong navy blue blazer with a distinctive striped pocket lining detail, available in sizes L and 2XL. The deep navy tone and tailored cut deliver a classic, authoritative formal look, while the pocket detail adds an elegant finishing touch.",
    category: "Mens Wear",
    subcategory: "Blazers",
    price: 145000,
    costPrice: 145000,
    stock: 2,
    barcode: "219191111106",
    tags: ["finelong", "blazer", "navy blue", "striped pocket", "formal", "mens", "tailored", "L", "2XL"],
  },
  {
    sku: "219191011105",
    name: "Finelong Suede With Sequin Blazer 2XL",
    description: "A dazzling Finelong blazer in size 2XL combining luxurious suede texture with sequin embellishments. The bold combination of materials creates a show-stopping piece for gala events, performances, and any occasion that demands maximum impact.",
    category: "Mens Wear",
    subcategory: "Blazers",
    price: 170000,
    costPrice: 170000,
    stock: 1,
    barcode: "219191011105",
    tags: ["finelong", "blazer", "suede", "sequin", "bold", "formal", "mens", "2XL", "embellished"],
  },
  {
    sku: "219199111073",
    name: "Finelong Silver & Purple Stripes Blazer XL 2XL",
    description: "A striking Finelong blazer in silver and purple stripes, available in XL and 2XL. The bold color combination and dynamic stripe pattern make this an unmissable choice for the man who wants to make a powerful, stylish statement at formal events.",
    category: "Mens Wear",
    subcategory: "Blazers",
    price: 145000,
    costPrice: 145000,
    stock: 3,
    barcode: "219199111073",
    tags: ["finelong", "blazer", "silver", "purple", "striped", "formal", "mens", "XL", "2XL"],
  },
  {
    sku: "219198111036",
    name: "Finelong Paul Eneche One Side Striped Blazer XL 2XL",
    description: "A unique Finelong blazer featuring a signature single-sided stripe design, named for its bold, dynamic detailing. Available in XL and 2XL, this blazer is tailored for the fashion-forward man who wants a distinctive and powerful look.",
    category: "Mens Wear",
    subcategory: "Blazers",
    price: 160000,
    costPrice: 160000,
    stock: 2,
    barcode: "219198111036",
    tags: ["finelong", "blazer", "striped", "one side", "formal", "mens", "XL", "2XL"],
  },
  {
    sku: "219196111096",
    name: "Finelong Grey Suit Set Bold Striped 2XL XL",
    description: "A powerful Finelong grey suit set with bold, wide stripes in sizes XL and 2XL. The commanding stripe pattern and structured tailoring create a confident, fashion-forward formal silhouette that stands apart from the conventional.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 185000,
    costPrice: 185000,
    stock: 2,
    barcode: "219196111096",
    tags: ["finelong", "suit", "grey", "bold striped", "formal", "tailored", "mens", "XL", "2XL"],
  },
  {
    sku: "219195111073",
    name: "Finelong Ash Suit & Trouser Black Lined Pocket L XL 3XL",
    description: "A refined Finelong ash grey suit and trouser set with black-lined pocket detailing, available in L, XL, and 3XL. The clean ash colour and sharp black accent elements create a polished, authoritative look for any formal occasion.",
    category: "Mens Wear",
    subcategory: "Suits & Sets",
    price: 185000,
    costPrice: 185000,
    stock: 3,
    barcode: "219195111073",
    tags: ["finelong", "suit", "ash", "grey", "black", "pocket", "formal", "tailored", "mens", "L", "XL", "3XL"],
  },

  // ───────────────────── 2-PIECE SETS ─────────────────────
  {
    sku: "219191811102",
    name: "K-BEJ Color 2-Piece Pant Set Jacob Cohen M L XL 2XL 3XL",
    description: "A luxurious two-piece pant set from Jacob Cohen in a distinctive K-BEJ colorway, available from M to 3XL. Jacob Cohen is celebrated for its exceptional Italian craftsmanship and premium denim and fabric, making this coordinated set a statement in refined casual luxury.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 220000,
    costPrice: 220000,
    stock: 4,
    barcode: "219191811102",
    tags: ["jacob cohen", "2 piece", "set", "pant set", "designer", "mens", "luxury", "italian", "M", "L", "XL"],
  },
  {
    sku: "219191431110",
    name: "2-Piece Hermes Black",
    description: "A sleek black two-piece set from Hermes. Crafted with the brand's hallmark precision and premium materials, this co-ordinated black set delivers understated luxury in a refined, versatile format perfect for smart-casual occasions.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 95000,
    costPrice: 95000,
    stock: 2,
    barcode: "219191431110",
    tags: ["hermes", "2 piece", "set", "black", "designer", "mens", "luxury", "french"],
  },
  {
    sku: "219191421110",
    name: "2-Piece Hermes Off White",
    description: "An elegant off-white two-piece set from Hermes. The warm neutral tone and the brand's impeccable tailoring create a refined, sophisticated look that transitions beautifully between smart-casual and semi-formal occasions.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 95000,
    costPrice: 95000,
    stock: 2,
    barcode: "219191421110",
    tags: ["hermes", "2 piece", "set", "off white", "cream", "designer", "mens", "luxury", "french"],
  },
  {
    sku: "219191011110",
    name: "Max One Black 2-Piece Set Line M L XL 2XL",
    description: "A sharp black two-piece coordinated set from Max One with a refined lined detail, available in M, L, XL, and 2XL. The clean black color and structured cut make this a versatile and effortlessly stylish ensemble for smart-casual and formal occasions.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 160000,
    costPrice: 160000,
    stock: 11,
    barcode: "219191011110",
    tags: ["max one", "2 piece", "set", "black", "mens", "M", "L", "XL", "2XL", "lined"],
  },
  {
    sku: "219191041110",
    name: "Max One White 2-Piece Set M L XL 2XL",
    description: "A crisp white two-piece coordinated set from Max One, available in M, L, XL, and 2XL. The clean all-white silhouette and well-tailored cut make this a striking and versatile choice for warm-weather events and special occasions.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 160000,
    costPrice: 160000,
    stock: 12,
    barcode: "219191041110",
    tags: ["max one", "2 piece", "set", "white", "mens", "M", "L", "XL", "2XL"],
  },
  {
    sku: "219191031110",
    name: "Max One White 2-Piece Jet Line Set M L XL 2XL",
    description: "A premium white two-piece jet-line set from Max One, available in sizes M to 2XL. The jet-line detailing adds a sleek, architectural edge to the clean white fabric, creating a contemporary formal set with distinctive character.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 165000,
    costPrice: 165000,
    stock: 12,
    barcode: "219191031110",
    tags: ["max one", "2 piece", "set", "white", "jet line", "mens", "M", "L", "XL", "2XL"],
  },
  {
    sku: "219191021110",
    name: "Max One Navy Green 2-Piece Set Lined M L XL 2XL",
    description: "A sophisticated navy green two-piece lined set from Max One, available in M, L, XL, and 2XL. The rich tonal color and lined construction combine for a premium, well-structured ensemble that commands attention at smart-casual and formal events.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 160000,
    costPrice: 160000,
    stock: 12,
    barcode: "219191021110",
    tags: ["max one", "2 piece", "set", "navy green", "lined", "mens", "M", "L", "XL", "2XL"],
  },
  {
    sku: "219192111103",
    name: "Beige Christian Dior 2-Piece Set M L XL 2XL 3XL",
    description: "An exquisitely tailored beige two-piece set bearing the Christian Dior label, available from M to 3XL. This coordinated ensemble channels the French luxury house's mastery of elegant proportions and premium fabric, delivering a look of effortless high-fashion authority.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 250000,
    costPrice: 250000,
    stock: 4,
    barcode: "219192111103",
    tags: ["christian dior", "dior", "2 piece", "set", "beige", "designer", "mens", "luxury", "french"],
  },
  {
    sku: "219191711100",
    name: "Grey 2-Piece Pant Set Jacob Cohen M L XL 2XL 3XL",
    description: "A sophisticated grey two-piece pant set from Jacob Cohen, available from M to 3XL. Renowned for their exceptional denim and fabric mastery, Jacob Cohen brings Italian precision and luxury to this versatile coordinated grey set.",
    category: "Mens Wear",
    subcategory: "2-Piece Sets",
    price: 220000,
    costPrice: 220000,
    stock: 5,
    barcode: "219191711100",
    tags: ["jacob cohen", "2 piece", "set", "grey", "pant set", "designer", "mens", "luxury", "italian"],
  },
];

async function seed() {
  const uri = process.env.MONGO_URI || "mongodb://localhost:27017/kentaz";
  await mongoose.connect(uri);
  console.log("Connected to MongoDB:", uri);

  let inserted = 0;
  let skipped = 0;

  for (const item of products) {
    const slug = slugify(item.name);
    const existing = await Product.findOne({
      $or: [{ barcode: item.barcode }, { slug }],
    });

    if (existing) {
      console.log(`SKIP  [${item.barcode}] "${item.name}" — already exists`);
      skipped++;
      continue;
    }

    await Product.create({
      name: item.name,
      slug,
      description: item.description,
      category: item.category,
      subcategory: item.subcategory,
      images: [],
      variants: [
        {
          sku: item.sku,
          price: item.price,
          costPrice: item.costPrice,
          stock: item.stock,
        },
      ],
      tags: item.tags,
      status: "published",
      barcode: item.barcode,
    });

    console.log(`INSERT [${item.barcode}] "${item.name}"`);
    inserted++;
  }

  console.log(
    `\nDone. ${inserted} inserted, ${skipped} skipped out of ${products.length} total.`
  );
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
